### ISSUE TITLE
Nova Funcionalidade: Relatório de erros ao salvar em uma janela separada

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#101]
Quando o banco de dados rejeita uma feição, é exibido um alerta no QGIS. Quando tenta-se salvar uma feição com problemas juntamente a outras, não há como saber imediatamente qual feição está com problemas. Sugere-se a implementação de um visualizador de problemas ao salvar, com a possibilidade de dar zoom para a feição com problemas e abrir o formulário de feição da mesma.

**Comment by dinizime** [comment]
Testamos esse conceito porém não funciona tão bem pois o PostGIS não retorna todos os problemas que ocorrem ao salvar.  Acredito que podemos fechar até fundamentar melhor o caso de uso.
