### ISSUE TITLE
Nova Funcionalidade: Processo de validação para identificação de erros de ligação

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#104]
No processo produtivo da DSG existe a etapa de confrontar cartas vizinhas para que se possa garantir a coerência entre as duas, etapa denominada de Ligação. Nesta etapa são verificados aspectos geométricos e de atributos. Sugere-se o uso da moldura como referência e um objeto auxiliar seria criado como resultado do seccionamento da moldura com os objetos que a tocam. Tais objetos possuem os atributos dos elementos originais e esses segmentos são confrontados com a carta vizinha para detectar possíveis inconsistências geométricas e de atributos.

**Comment by dinizime** [comment]
Esse processing entrou na nossa lista de prioridade.
Uma vez implementado e testado em produção ele será integrado ao DSGTools.

**Comment by dinizime** [comment]
Teste em produção iniciado
