### ISSUE TITLE
Nova Funcionalidade: Gerar molduras que cobrem determinadas feições

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#105]
O plugin Grid Zone Generator permite a criação de molduras a partir de uma moldura de uma escala menor. Sugere-se uma evolução, na qual seriam criadas molduras de uma determinada escala necessárias para cobrir totalmente feições de uma camada de entrada. Como exemplo, pode-se citar o problema de encontrar todas as cartas na escala 25.000 necessárias para mapear um determinado estado.

**Comment by jpesperidiao** [comment]
Já materializado no alg 'Generate Systematic Grid Related to Layer" que o @phborba fez (disponível na 4.1_dev).
