### ISSUE TITLE
Nova Funcionalidade: Gerador de bancos sumarizados

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#110]
Foi elaborado pelo 1º e 2º CGEO uma proposta de EDGV Pro (anteriormente denominada EDGV Sumarizada) e esta proposta foi avaliada pelos demais centros. Da avaliação realizada, surgiu um requisito de, para determinados projetos, resgatar atributos da norma completa. Sendo assim, pensou-se numa rotina de adicionar atributos e classes excluídas na sumarização, para atender demandas específicas.

**Comment by phborba** [comment]
@dinizime  isso ainda faz sentido?

**Comment by dinizime** [comment]
Na visão atual não. A produção da DSG deve ser um perfil da EDGV, contendo somente um subconjunto de atributos para produção. Caso seja necessário utilizar outros atributos utilizar o perfil completo da EDGV.
