### ISSUE TITLE
Nova Funcionalidade: Extrair informações de um raster a partir de um conjunto de pontos

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#114]
Deseja-se uma ferramenta semelhante ao Point on raster overlayer existente no FME. Essa ferramenta permite que dado um conjunto de pontos, estes seriam confrontados a um raster e uma informação da célula do raster correspontente ao posicionamento do ponto seria armazenada como atributo do ponto. Uma aplicação prática dessa nova funcionalidade seria extrair informações de cota de um MDS a partir de um conjunto de pontos. O QGIS já possui formas de executar esse procedimento, porém deseja-se um fluxo mais adequado ao processo produtivo da DSG.

**Comment by jpesperidiao** [comment]
Ferramenta `Set Value From Raster`.
