### ISSUE TITLE
Nova Funcionalidade: Verificador ortográfico

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#117]
Foi relatado pelo 3º CGEO que ao longo dos anos do projeto Bahia, foi constatado um grande número de erros identificados pelos revisores devido a incorreções ortográficas. Para diminuir os erros, foi desenvolvido pelo 3º CGEO um script que exporta informações textuais para um arquivo CSV, em seguida esse arquivo é aberto no libreoffice, as correções são feitas por meio do seu corretor ortográfico e, por fim, o arquivo é reimportado no banco de dados. Foi solicitado que esse procedimento fosse todo feito por meio do QGIS/DSGTools. É desejável que se tenha um procedimento de verificação de inconsistências com geração de flags apontando os erros. Além disso, também é desejável que exista um procedimento para verificação em tempo real no momento em que o operador está preenchendo a tabela de atributos.

**Comment by dinizime** [comment]
Desenvolvido um protótipo e estará em testes para futura integração com DSGTools

**Comment by dinizime** [comment]
Nova versão implementada. Teste em produção iniciado.
