### ISSUE TITLE
Nova Funcionalidade: Banco de topônimos (nomes geográficos)

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#118]
Foi solicitado que fosse implementado um banco de dados que armazenaria um conjunto de nomes geográficos a serem utilizados em determinado projeto, para fins de padronização no preenchimento.

**Comment by dinizime** [comment]
Não parece ser uma funcionalidade do DSGTools. Caso a DSG defina uma modelagem padrão para banco de topônimos (como geonames da NGA) podemos rever esse issue.

**Comment by phborba** [comment]
Concordo, esse issue foi aberto na época do relatório do curso e acho que hoje em dia não faz mais sentido. E se for necessário implementar, não acho que tem que ser no DSGTools, teria que ser um sistema a parte.
