### ISSUE TITLE
Help: Atualizar conteúdo do help

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#150]
- Verificar informações desatualizadas e alterá-las para as novas interfaces;
- Verificar a possibilidade de acrescentar gifs explicativos.

**Comment by phborba** [comment]
@jpesperidiao atentar para a observação do issue #43

**Comment by rsmaior** [comment]
Na parte de validação:
1) Falta documentar diversos processos de validação
2) Recomendo utilizar uma lista dos processos ordenada e coerente com a lista no plugin. 
Ex: No plugin temos 
"Process #1 Clean Geometries"
"Process #2 Close Earth Coverage Polygons"
É interessante colocar a documentação na mesma ordem em que aparecem os processos no plugin e usar a mesma numeração para os processos

**Comment by phborba** [comment]
@jpesperidiao não esquece de colocar o nome do Wallace no manual também, por favor, já que ele fez a revisão completa e apontou uma porrada de coisas.

**Comment by jpesperidiao** [comment]
Praticamente completo para a versão 3.0.8. Faltam os processos de validação que já não tinham sido explicados ou que não tinha um banco pronto pra testar.

Já dá pra ir revisando e pedindo _feedback_.
