### ISSUE TITLE
Definir enquadramento de feições linha e área no inspetor de feições

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#158]
Uma melhoria ao inspetor de feições seria definir dar opção ao usuário de definir um enquadramento a feições linha e área.
Em geral após navegar em uma feição linha ou área o usuário tem que dar um zoom out para ver o contexto da feição. Seria interessante ter um drop down para escolher o enquadramento. Neste caso não deve ser em escala do mapa, mas em % do mbr do objeto por exemplo.

**Comment by phborba** [comment]
Feito no commit a75975ce569ba49d03658c5e99fe749689fed982
