### ISSUE TITLE
Problema ao rodar processos de validação com tabelas com geometria do tipo GEOMETRY

### ISSUE THREAD

**Issue by lcoandrade** [dsgoficial/DsgTools#165]
### Subject of the issue (Assunto do problema)
Problema ao usar bancos com tabelas cuja geometria estaja marcada como "GEOMETRY".

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Linux Ubuntu
* version of QGIS (Versão do QGIS): 2.18.14
* version of DSGTools (Versão do DSGTools): 3.1_dev

### Steps to reproduce (Passos para reproduzir)
Ao tentar rodar processos de validação em tabelas com coluna geométrica do tipo GEOMETRY a camada referente não é carregada dando uma exceção.

### Expected behaviour (Comportamento esperado)
Espera-se que, caso não seja possível rodar o processo por haver colunas do tipo GEOMETRY, que haja informação do motivo para o usuário. Ou talvez nem dar a possibilidade de usar elas. Não sei ao certo.

### Actual behaviour (Comportamento atual)
O processo não é executado e ocorre uma falha que é registrada porém, sem maiores informações ao usuário.

**Comment by phborba** [comment]
Resolvido no commit 0f85c6964d9fd9cf355f334e391d7153d356aebf
