### ISSUE TITLE
layers com tabela de atributos vazia

### ISSUE THREAD

**Issue by ratitu** [dsgoficial/DsgTools#176]
### Subject of the issue (Assunto do problema)
quando tento carregar os layers eles sao carregados no projeto, mas sem nenhum dado. As tabelas de atributos não contem nenhuma informação

### Your environment (Seu ambiente)
* your operating system (ubuntu 16.04): 
* version of QGIS (2.18.15): 
* version of DSGTools (3.0.8): 

### Steps to reproduce (Passos para reproduzir)
DSGtools -> layer tools -> load layers

**Comment by ratitu** [comment]
warning:/home/ratitu/.qgis2/python/plugins/DsgTools/Factories/LayerLoaderFactory/postgisLayerLoader.py:320: DeprecationWarning: QgsVectorLayer.setEditorWidgetV2Config() is deprecated
			  lyr.setEditorWidgetV2Config(i,valueRelationDict)
			
			traceback:  File "/home/ratitu/.qgis2/python/plugins/DsgTools/dsg_tools.py", line 910, in loadLayersFromServer
			    result = dlg.exec_()
			  File "/home/ratitu/.qgis2/python/plugins/DsgTools/LayerTools/LoadLayersFromServer/loadLayersFromServer.py", line 163, in on_buttonBox_accepted
			    factoryDict[dbName].load(selectedClasses, uniqueLoad=uniqueLoad, onlyWithElements=withElements, stylePath=selectedStyle, useInheritance=onlyParents, isEdgv=isEdgv, parent=self)
			  File "/home/ratitu/.qgis2/python/plugins/DsgTools/Factories/LayerLoaderFactory/postgisLayerLoader.py", line 160, in load
			    vlayer = self.loadLayer(lyr, groupDict[prim][cat], loadedLayers, useInheritance, useQml, uniqueLoad, stylePath, domainDict, multiColumnsDict, domLayerDict, edgvVersion)
			  File "/home/ratitu/.qgis2/python/plugins/DsgTools/Factories/LayerLoaderFactory/postgisLayerLoader.py", line 221, in loadLayer
			    vlayer = self.setDomainsAndRestrictions(vlayer, tableName, domainDict, multiColumnsDict, domLayerDict)

**Comment by phborba** [comment]
Muito obrigado pelo feedback! @ratitu você havia produzido algum dado para o seu banco ou importado algum dado para ele? Caso negativo, a título de informação, o DSGTools não provê nativamente dados. Ele provê uma implementação da EDGV previamente elaborada para que pessoas possam produzir dados em concordância com a norma supracitada. 

Quanto ao warning, isso não é erro, é aviso de coisas que foram utilizadas no código que em versões futuras do QGIS não serão mais suportadas. Isso não é erro, dado que o plugin funciona normalmente. Basicamente são avisos para os programadores de que em versões futuras alterações no código serão necessárias, entende?

**Comment by phborba** [comment]
@ratitu sua dúvida foi respondida?

**Comment by phborba** [comment]
Vou fechar a issue e qualquer coisa reabra novamente ok @ratitu ?
