### ISSUE TITLE
Melhoria na Ferramenta de Validação

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#177]
Seria interessante guardar mais atributos no histórico de execução:
- usuario: nome do usuario da conexão que executou o algoritmo
- parametros: caso a rotina tenha algum parametro guardar de forma textual o nome e o valor (separado por dois pontos, e parametros distintos separados por virgula por exemplo)
- camadas: lista separada por virgula com as camadas utilizadas na rotina
- nr_flags: número de flags na execução na rotina

**Comment by phborba** [comment]
Relacionado ao issue #73

**Comment by jpesperidiao** [comment]
Pessoal, duas dúvidas:

+ camadas já não parâmetros do processo?
+ é pra alterar as mensagens de log ou o histórico de execução que é aberto pelo botão `Abrir Histórico`?

**Comment by jpesperidiao** [comment]
Bom, assumi que fosse do _log_, por já existir o método ```logProcess()``` pré-implementado (vazio).
Interpretei, também, que as camadas, por serem um parâmetro do processo, não seriam repetidas no _log_, apenas no campo parâmetros.

Terminei a implementação desta função e atualizei a função de execução de processo para que reproduzisse este _log_.

_Commit_ [d972823](https://github.com/dsgoficial/DsgTools/commit/d972823df4620b410c601d598d1b4646dda6638e).

Vou começar agora uma pré-implementação de histórico de execução, que pode ser descartada, caso achem melhor. Assim que terminar, coloco o _link_ para o _commit_ final.

**Comment by phborba** [comment]
@jpesperidiao quando vc pegar o self.parameter[key], vc vai pegar o objeto de parâmetro, que pode ser número, texto, ou um dicionário escroto. Nesses casos de dicionário, é bom tratar para ficar mais palatável, pq se não a leitura não vai ficar muito agradável. Amanhã te oriento melhor sobre isso.

**Comment by jpesperidiao** [comment]
Alterados os Log e tabela de histórico. Se puderem, deem uma testada. Mexi também nos também de execução por camada de cada processo (estavam dado o tempo cumulativo em vez do tempo de execução por camada).

Feito no commit [09c8166](https://github.com/dsgoficial/DsgTools/commit/09c81660409db5da628ec5da3f4c0bb7c2ff6094) do branch 3.1_dev_ValidationToolEnhancement_#177.

**Comment by phborba** [comment]
@dinizime feito no commit 09c81660409db5da628ec5da3f4c0bb7c2ff6094 pelo @jpesperidiao 

Pode testar depois por favor?

**Comment by dinizime** [comment]
Domínio resolvido OK. Informações adicionais aparecem no log somente.
Porém acredito que temos que repensar a forma que o log funciona, não está em um formato eficiente para uso do validador, ou de uma auditoria das rotinas executadas no banco de dados.

**Comment by phborba** [comment]
Concordo, mas estou pensando em mudar isso somente na 3.2, o que vc acha @dinizime ?
