### ISSUE TITLE
Melhoria para a Ferramenta de Seleção Genérica: Criar um rubberband para a feição selecionada no combo de seleção de feições

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#180]
Criar um rubberband iluminando a feição candidata a seleção.

Sugestão: usar os sites dos comentários do issue #69

**Comment by jpesperidiao** [comment]
Feito no commit [37b4e7b](https://github.com/dsgoficial/DsgTools/commit/37b4e7bb472608a32c337d45324316675f1e2080) do branch [3.2_dev_GenericSelection_#180](https://github.com/dsgoficial/DsgTools/tree/3.2_dev_GenericSelection_%23180).

**Comment by jpesperidiao** [comment]
Pequenas alterações de cor e transparência no commit [cb8c793](https://github.com/dsgoficial/DsgTools/commit/cb8c793d7ce1b26eb6b7e8d35763b401590280eb).

**Comment by jpesperidiao** [comment]
@phborba, vê agora foi!

**Comment by phborba** [comment]
Agora foi, posso fazer o merge?

**Comment by jpesperidiao** [comment]
Pode!
