### ISSUE TITLE
Bug na Ferramenta de inspeção de feições

### ISSUE THREAD

**Issue by emxav** [dsgoficial/DsgTools#181]
### Subject of the issue (Assunto do problema)
A "Ferramenta de inspeção de feições" apresenta um erro a cada nova feição selecionada (botão Next).

### Your environment (Seu ambiente)
* SO Linux OpenSUSE
* QGIS 2.18.15
* DSGTools 3.0.8

### Steps to reproduce (Passos para reproduzir)
Em um layer do tipo Shapefile, a cada nova feição, aparece um "Erro Python".

### Expected behaviour (Comportamento esperado)
Sem msg de erro.

### Actual behaviour (Comportamento atual)
Pilha:
Um erro ocorreu enquanto executava o código Python: 

UnboundLocalError: local variable 'oldId' referenced before assignment 
Traceback (most recent call last):
  File "/home/emerson/.qgis2/python/plugins/DsgTools/ProductionTools/InspectFeatures/inspectFeatures.py", line 162, in setNewId
    if oldId == newId:
UnboundLocalError: local variable 'oldId' referenced before assignment

Versão do Python: 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC] 
Versão do QGIS: 2.18.15 Las Palmas, exported 

Caminho do Python:
/usr/share/qgis/python/plugins/processing
/usr/share/qgis/python
/home/emerson/.qgis2/python
/home/emerson/.qgis2/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python27.zip
/usr/lib64/python2.7
/usr/lib64/python2.7/plat-linux2
/usr/lib64/python2.7/lib-tk
/usr/lib64/python2.7/lib-old
/usr/lib64/python2.7/lib-dynload
/usr/lib64/python2.7/site-packages
/usr/lib64/python2.7/site-packages/PIL
/usr/local/lib64/python2.7/site-packages
/usr/local/lib/python2.7/site-packages
/usr/lib64/python2.7/site-packages/gtk-2.0
/usr/lib/python2.7/site-packages
/usr/lib64/python2.7/site-packages/wx-3.0-gtk2
/home/emerson/.qgis2//python
/home/emerson/.qgis2/python/plugins/DsgTools
/home/emerson/.qgis2/python/plugins/DsgTools/ProductionTools/CopyPasteTool
/dados/2_SSA

**Comment by phborba** [comment]
@emxav não consegui replicar. Tem que criar uma feição nova enquanto está iterando? Se for isso, aqui deu tudo certo. Teria como explicar melhor por favor?

**Comment by phborba** [comment]
Consegui replicar ao trocar manualmente o id no line edit, era isso?

**Comment by phborba** [comment]
Corrigido no commit 20a6786734da3a1a21fc605d6d5fa3aee31b8ffe do branch 3.1_dev
@emxav o senhor pode testar por favor?

**Comment by emxav** [comment]
Creio que o problema ocorreu porque o layer SHP não tinha nenhuma coluna "ID". A geometria é POL.

**Comment by phborba** [comment]
Acho que não era bem isso, pois testei com shp do BDGEx que não tem coluna id. No código iteramos pelo featureId, que é o id que o QGIS cria internamente para controlar as feições. Ele cria esse código para contornar os formatos que não possuem chave primária. Consegui replicar quando mexi no line edit e entrei o id na mão. Acredito que agora foi corrigido, quando o senhor testar o senhor pode me avisar para fechar o ticket, por favor?

**Comment by emxav** [comment]
Fala @phborba. Fiz um Q&D aqui e joguei o arquivo do commit na produção.

Parou de aparecer o erro, agora aparece **outro**, mas por um breve período (2 segundos):

![screenshot_20171228_174752](https://user-images.githubusercontent.com/34849707/34422974-ca445ace-ebf7-11e7-9265-e3fa476260f7.png)

**Comment by phborba** [comment]
@emxav mas ele itera para o próximo mesmo assim?

**Comment by emxav** [comment]
Sim. Funciona conforme esperado (vai pro próximo). Mas chama o código como se `oldIndex == newId`.

**Comment by emxav** [comment]
Fala @phborba .
Tentei outra abordagem a partir da L155. Troquei o `oldIndex` por `oldId`. Esse nome é usado mais adiante, no `except:`. Depois comentei a msg de erro. Segue.

```
oldId = self.allLayers[lyrName]
if oldId == 0:
    return
featIdList = self.getFeatIdList(currentLayer)
if oldId not in featIdList:
    oldId = 0
zoom = self.mScaleWidget.scale()
if oldId == newId:
    #self.iface.messageBar().pushMessage(self.tr('Warning!'), ...
    return
```

**Comment by phborba** [comment]
@emxav nos commits que fiz hoje de tarde ajeitei o que o senhor sugeriu, porém não comentei o warning, dado que ele está lá para o caso do usuário digitar um id que não existe. Repliquei o que o senhor descreveu e não achei mais erro. Vou fechar o issue e qualquer coisa reabrimos, ok?
