### ISSUE TITLE
Bug na rotação de gabarito

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#182]
### Subject of the issue (Assunto do problema)
No issue #64, foi implementada a rotação de gabarito. Quando o gabarito está rotacionado e o usuário clica, o cursor some.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): MacOS High Sierra
* version of QGIS (Versão do QGIS): 2.18.14
* version of DSGTools (Versão do DSGTools): 3.1_dev_MinimumAreaTool_#64

### Steps to reproduce (Passos para reproduzir)
Rotacionar o gabarito (com o control segurado) e clicar, sem mover o mouse.

### Expected behaviour (Comportamento esperado)
Desativar a ferramenta e o cursor do QGIS ser reestabelecido.

### Actual behaviour (Comportamento atual)
Cursor some.

**Comment by jpesperidiao** [comment]
Bug consertado no commit [2d67d2e](https://github.com/dsgoficial/DsgTools/commit/2d67d2e6f1a93ebe10617cfd4abc24780baa6f37).
