### ISSUE TITLE
Implementar a EDGV 3.0

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#183]
A EDGV 3.0 foi homologada na CONCAR e o modelo físico deve ser implementado.

**Comment by phborba** [comment]
EDGV 3.0 Implementada, falta testar.

**Comment by phborba** [comment]
Pendências:

- [ ] Trigger de explodir geometrias
- [ ] Trigger de tornar null
- [ ] Ajustar defaults dos multi valorados
- [ ] Tabela de carregamento de multivalorado interno ao banco, ao invés de qml (para o Postgres)
- [ ] Estudar a possibilidade de colocar o qml interno ao spatialite

**Comment by dinizime** [comment]
É requisito a implementação da EDGV 3.0 em spatialite realmente? Não seria o momento para pensar em Geopackage?

**Comment by phborba** [comment]
Vou colocar o spatialite só pra teste, a ideia é em versão futura colocar o geopackage.
