### ISSUE TITLE
Algumas classes estão com id do tipo UUID

### ISSUE THREAD

**Issue by lcoandrade** [dsgoficial/DsgTools#185]
### Subject of the issue (Assunto do problema)
Describe your issue here. (Descreva seu problema aqui).
As seguintes classes do modelagem 2.1.3 possuem a pk do tipo uuid. Isso impossibilita o uso das ferramentas de validação nelas:
cb.loc_localidade_p
cb.loc_vila_p
cb.loc_vila_p
cb.loc_capital_p
cb.loc_aglomerado_rural_p
cb.loc_aglomerado_rural_isolado_p
cb.loc_aglom_rural_de_ext_urbana_p

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Kubuntu 14.04
* version of QGIS (Versão do QGIS): 2.18.14
* version of DSGTools (Versão do DSGTools): 3.1_dev

### Steps to reproduce (Passos para reproduzir)
Tell us how to reproduce this issue. Please provide screenshots to further information. (Descreva os passos para reproduzir o problema. Por favor informe capturas de tela para informaçes adicionais)
Tentar rodar processos de validação em qualquer uma das classes acima.

### Expected behaviour (Comportamento esperado)
Tell us what should happen. (Nos informe o que deveria acontecer.)
As pk deveriam ser do tipo inteiro, possibilitando o uso das ferramentas de validação.

### Actual behaviour (Comportamento atual)
Tell us what happens instead. (Nos informe o que acontece ao executar o procedimento descrito.)
Erro na execução de processos nas referidas classes.

**Comment by phborba** [comment]
Resolvido no commit bd730bea1999f9064c66e607b79e2d0bc30a483f

**Comment by lcoandrade** [comment]
Existem ainda os ALTER TABLE referente às classes mencionadas. Iniciando na linha 17347 do arquivo edgv213.sql.

**Comment by phborba** [comment]
Resolvido no commit 8cbc2fdb7b69c5fa373780088af3bdafc57d01a7
