### ISSUE TITLE
Fechar Form ferramenta de ângulo reto e círculo

### ISSUE THREAD

**Issue by desenv-1dl** [dsgoficial/DsgTools#188]
### Subject of the issue (Assunto do problema)
Describe your issue here. (Descreva seu problema aqui).
É necessário fechar o formulário quando for definido a opção suprimir formulário nativa do Qgis.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): 
Windows e Debian.

* version of QGIS (Versão do QGIS): 
2.18.15
* version of DSGTools (Versão do DSGTools): 
3.1

### Expected behaviour (Comportamento esperado)
Tell us what should happen. (Nos informe o que deveria acontecer.)
Deveria ser possivel suprimir o formulario

### Actual behaviour (Comportamento atual)
Tell us what happens instead. (Nos informe o que acontece ao executar o procedimento descrito.)
A ferramenta sempre abre o formulário.

**Comment by phborba** [comment]
@dinizime @desenv-1dl corridgido no commit 025630db80bd3678d4df4f3cbd2cabe0f130fe10

Podem testar por favor?
