### ISSUE TITLE
Habilitar o uso da ferramenta de aquisição em círculo para feições de geometria linha

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#189]
### Subject of the issue (Assunto do problema)
Habilitar o uso da ferramenta de aquisição em círculo para feições de geometria linha. O caso mais comum é a construção de rotatórias.

De forma a criar um circulo linear sem self intersect o ideal é que o circulo ao ser inserido seja divido em duas feições.

obs: A ferramenta de ângulos retos poderia também possibilitar a aquisição em feições do tipo linha, porém não consigo imaginar casos de uso na produção neste momento (talvez em cadastro.. muros..)

**Comment by phborba** [comment]
@dinizime feito, pode testar por favor?

**Comment by dinizime** [comment]
Funcionando!
