### ISSUE TITLE
Problema na consulta do Identificar vértices próximo a arestas

### ISSUE THREAD

**Issue by lcoandrade** [dsgoficial/DsgTools#192]
### Subject of the issue (Assunto do problema)
A consulta utilizada é feita para rodar tanto com linha como áreas, porém para o caso de linhas o trecho de consulta a seguir retornará apenas os pontos inicial e final das partes (caso sejam multiparte) das mesmas:

(ST_Dump(ST_Boundary("{2}"))).geom

Para o caso de linhas não deve haver o uso do ST_Boundary. Sendo assim a fábrica de consultas deve retornar a consulta correta de acordo com o tipo de camada testada.

**Comment by phborba** [comment]
Corrigido no commit 3c2363a985104d6b12a3486af08a164e95a5e76f

**Comment by lcoandrade** [comment]
Pequeno ajuste no commit f2f331b.
