### ISSUE TITLE
Comportamento dos botões Ok e Cancelar do ajuste da Cobertura Terrestre

### ISSUE THREAD

**Issue by jpesperidiao** [dsgoficial/DsgTools#194]
### Subject of the issue (Assunto do problema)
Ao se clicar no botão `Cancelar`, há a emissão de um alerta tal qual tivesse clicado `Ok` sem selecionar uma configuração a ser apagada.

Quanto ao botão `Ok`, este, quando clicado sem configuração selecionada, encerra a janela.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Kubuntu 16.04
* version of QGIS (Versão do QGIS): 2.18.12
* version of DSGTools (Versão do DSGTools): 3.08

### Steps to reproduce (Passos para reproduzir)
Clicar nos botões sem selecionar quaisquer configurações.

### Expected behaviour (Comportamento esperado)
`Cancelar` > encerrar a caixa de diálogo sem quaisquer avisos.
`Ok` > emitir o alerta mantendo, porém, a caixa de diálogo aberta.

### Actual behaviour (Comportamento atual)
Conforme descriação do problema.

**Comment by jpesperidiao** [comment]
Sugiro verificar todos os outros `Cancelar` e comportamentos ao pressionar ```Esc``` , uma vez que há o mesmo comportamento com outras caixas de diálogo desta ferramenta.

**Comment by jpesperidiao** [comment]
Esse é um excelente exemplo de como ___NÃO___ realizar um reporte de problema...

Ou o problema já foi consertado, ou eu não entendi o que eu mesmo quis dizer. hahah

**Comment by jpesperidiao** [comment]
Resolvido pelo @lcoandrade no commit [27009ea](https://github.com/dsgoficial/DsgTools/commit/27009eaf755ab30cffaed693d5a317e6d68a63a5). Foi no branch [3.2_dev_ValidationToolBox_#209](https://github.com/dsgoficial/DsgTools/tree/3.2_dev_ValidationToolBox_%23209) porque eu passei o bizu errado.

**Comment by phborba** [comment]
Conferi e acho que está ok. Vou fechar o issue.
