### ISSUE TITLE
Erro ao deletar configuração de reclassificação

### ISSUE THREAD

**Issue by jpesperidiao** [dsgoficial/DsgTools#195]
### Subject of the issue (Assunto do problema)
Erro Python ao deletar configuração de Reclassificação

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Kubuntu 16.04
* version of QGIS (Versão do QGIS): 2.18.12
* version of DSGTools (Versão do DSGTools): 3.08

### Steps to reproduce (Passos para reproduzir)
Criar uma configuração de reclassificação e tentar deletar a configuração depois.

### Expected behaviour (Comportamento esperado)
Apagar a configuração criada.

### Actual behaviour (Comportamento atual)
Não apaga a configuração, mantém a janela aberta e travada e dá o seguinte erro:

Um erro ocorreu enquanto executava o código Python: 

```diff
TypeError: sequence item 0: expected string, NoneType found 
Traceback (most recent call last):
  File "/home/proc/.qgis2/python/plugins/DsgTools/CustomWidgets/genericManagerWidget.py", line 530, in deleteSelectedSetting
    self.outputMessage(operation, header, successDict, exceptionDict)
  File "/home/proc/.qgis2/python/plugins/DsgTools/CustomWidgets/genericManagerWidget.py", line 272, in outputMessage
    msg += self.tr(' on databases ') + ', '.join(successList)
TypeError: sequence item 0: expected string, NoneType found


Versão do Python: 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609] 
Versão do QGIS: 2.18.12 Las Palmas, a6c461b 
[...]
```

**Comment by phborba** [comment]
Resolvido no commit bd42393adf12bfa836749b91019dccd4e051f6be
