### ISSUE TITLE
Conflito Visualizar code list e valores

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#196]
### Subject of the issue (Assunto do problema)
Ao selecionar camadas que utilizem campos de mapa de valor porém não sigam o padrão do DSGTools ocorre o seguinte erro:

![image](https://user-images.githubusercontent.com/10109704/34884660-89083e46-f7a4-11e7-997d-d5585118a445.png)

Ao desligar o DSGTools em Complementos/Gerenciar e Instalar Complementos e clicar novamente em uma cada com mapa de valores que não siga o padrão do DSGTools o seguinte erro python ocorre:

![image](https://user-images.githubusercontent.com/10109704/34884825-185aac8c-f7a5-11e7-8a6a-ea26e6514d1b.png)

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Windows 10
* version of QGIS (Versão do QGIS):  2.18.14
* version of DSGTools (Versão do DSGTools): 3.1 dev

**Comment by phborba** [comment]
if self.currLayer.editFormConfig().widgetType(fieldIndex) in ['ValueMap', 'ValueRelation']:

**Comment by jpesperidiao** [comment]
Achei que não tinha resolvido. Mas abri aqui agora e só o botão `Reload` tava meio bugado.

Podem testar?

Último commit [b9c7de0](https://github.com/dsgoficial/DsgTools/commit/b9c7de05789901e34b1483e8e4c1894daa4e9b89) do branch 3.1_dev_CodeListViewer_#196.

**Comment by phborba** [comment]
<img width="310" alt="screen shot 2018-02-01 at 21 54 12" src="https://user-images.githubusercontent.com/6131641/35709623-82aade68-079a-11e8-833a-9dcd39b69e2d.png">

tá populando com bug

**Comment by jpesperidiao** [comment]
Fixed no commit [2796fde](https://github.com/dsgoficial/DsgTools/commit/2796fdea920da2cc29e03b9cffdda11f7a4c5b1c).

Pode confirmar?

**Comment by jpesperidiao** [comment]
Acho que resolve os dois problemas: 

- o de dar raise toda vez que clica em camadas (agora o codelist é ativamente selecionado pelo usuário e é independente de padrão EDGV); e
- a widget do CodeListViewer é criado seguindo o padrão acima, logo, independente de a camada incial ser ou não EDGV, ter ou não mapa de valor, os comboBox só são preenchidos por classes/camadas e atributos/campos que possuam/sejam mapas de valor.

@dinizime e @phborba

**Comment by lcoandrade** [comment]
Vi as mudanças aqui. Pra mim, até agora, está ok. 
A ideia agora e tornar um visualizador uma ferramenta que não dependa da seleção da camada? Pelo que vi, o uso dos try/except já resolveriam o problema de bancos não DSGTools. Essa seleção da camada na ferramenta pode ser chatinha se houver muitas camadas carregadas, algo que seria já resolvido com o uso do sinal.
O que me diz disso @jpesperidiao?

**Comment by phborba** [comment]
Sim, a ideia é essa. Não é bom ter uma componente do DSGTools q fica capturando sinal toda vez que algo muda, sem ela estar sendo usada. Ela só vai funcionar quando de fato o usuário quiser. O nosso plugin se torna menos intrusivo dessa forma. Para a quantidade excessiva de camadas, basta trocar o combo pelo como q permite busca.

**Comment by lcoandrade** [comment]
Então ok. O combo editável para busca fica melhor mesmo. O @jpesperidiao podia mudar isso antes do merge.

**Comment by phborba** [comment]
Tinha bug nas camadas q vinham do legendInterface, pq nem todas elas tem pendingFields (camadas vetoriais que tem). Logo, a forma de verificar isso é botar um isinstance(layer, QgsVectorLayer), q nem coloquei no commit 4d5cb8647470604c80306530fa088af96e314923
`
layers = self.iface.legendInterface().layers()
for layer in layers:
      if isinstance(layer, QgsVectorLayer):
...
`
