### ISSUE TITLE
Processo de identificação de geometrias duplicadas não encara como duplicadas linhas com orientações diferentes

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#198]
### Subject of the issue (Assunto do problema)
Describe your issue here. (Descreva seu problema aqui).
O processo de identificação de geometria duplicadas deveria identificar que a linha AB é igual à linha BA. Esse tipo de linha causa problema na importação para o grass, gerando flag no processo de limpeza.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Mac OS High Sierra
* version of QGIS (Versão do QGIS): 2.18.14
* version of DSGTools (Versão do DSGTools): 3.1

### Steps to reproduce (Passos para reproduzir)
Tell us how to reproduce this issue. Please provide screenshots to further information. (Descreva os passos para reproduzir o problema. Por favor informe capturas de tela para informaçes adicionais)
Rodar um processo de identificação de geometrias duplicadas em dados com linhas iguais, mas com orientações diferentes.
### Expected behaviour (Comportamento esperado)
Tell us what should happen. (Nos informe o que deveria acontecer.)
Linhas duplicadas com orientações diferentes deveriam ser encaradas como duplicadas.
### Actual behaviour (Comportamento atual)
Tell us what happens instead. (Nos informe o que acontece ao executar o procedimento descrito.)
Não é levantada flag, dado que com a consulta que é feita no banco, as geometrias são diferentes (WKB diferentes).

**Comment by lcoandrade** [comment]
Fiz uns testes aqui.
Analisei duas linhas presentes numa camada:
1 - MultiLineString ((0 0, 1 1))
2 - MultiLineString ((1 1, 0 0))

A consulta usada no processo, gerou apenas um grupo e levantou flag.
A consulta estava assim:
select * from (
        SELECT id,
        ROW_NUMBER() OVER(PARTITION BY geom ORDER BY id asc) AS Row,
        geom FROM ONLY tabela 
        ) dups

Trocando para:
select * from (
        SELECT id,
        ROW_NUMBER() OVER(PARTITION BY st_astext(geom) ORDER BY id asc) AS Row,
        geom FROM ONLY tabela 
        ) dups

Gera dois grupos.
Usando o objeto Geometry a comparação é feita com ST_Equals. Ao ler https://postgis.net/docs/ST_Equals.html, vi que a direcionalidade é ignorada.

Sendo assim, linhas quando comparadas com a suas reversas serão consideradas iguais pelo PostGIS.

Talvez o problema seja de igualdade de vértices, possivelmente problema de casas decimais. Melhor averiguar mais. Sugiro fechar a Issue.
