### ISSUE TITLE
Carregar camadas de um servidor some com Bancos de Dados

### ISSUE THREAD

**Issue by jpesperidiao** [dsgoficial/DsgTools#199]
### Subject of the issue (Assunto do problema)
Ao selecionar uma Versão da EDGV e um banco na ferramenta ```Carregar camadas de um servidor```, mudando a versão da EDGV e retornando, os bancos selecionados somem da lista de bancos.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Kubuntu 16.04
* version of QGIS (Versão do QGIS): 2.18.12
* version of DSGTools (Versão do DSGTools): 3.08

### Steps to reproduce (Passos para reproduzir)

1. Selecionar uma versão EDGV;
2. escolher um Banco de dados da lista;
3. trocar a versão EDGV; e
4. retornar a versão EDGV escolhida anteriormente.

### Expected behaviour (Comportamento esperado)
Lista de bancos disponível deveria conter os bancos selecionados antes, OU os bancos selecionados continuarem na lista de bancos selecionados.

### Actual behaviour (Comportamento atual)
Bancos selecionados somem das listas de bancos de dados da conexão de servidor escolhida.

**Comment by jpesperidiao** [comment]
Acho que resolvi no commit [c42dd0c](https://github.com/dsgoficial/DsgTools/commit/c42dd0c379c745cd827c3913be58c7c7b4dfb5da).

**Comment by jpesperidiao** [comment]
branch 3.1_dev_ComplexFeatureTool_#199

**Comment by phborba** [comment]
Resolvido
