### ISSUE TITLE
Erro na inicialização do Dissolve

### ISSUE THREAD

**Issue by lcoandrade** [dsgoficial/DsgTools#202]
### Subject of the issue (Assunto do problema)
O processo Dissolve está dando erro ante de ser iniciado de fato. Isto está ocorrendo na hora de montar o processChain. Ao remover o método de pré-processo, funciona.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): macOS High Sierra
* version of QGIS (Versão do QGIS): 2.18.14
* version of DSGTools (Versão do DSGTools): 3.1_dev 

### Steps to reproduce (Passos para reproduzir)
Tentar rodar o Dissolve

### Expected behaviour (Comportamento esperado)
Conseguir rodar o Dissolve

### Actual behaviour (Comportamento atual)
Uma mensagem de erro aparece : 'NoneType' object is not iterable

**Comment by phborba** [comment]
Resolvido no commit 2f4aa6e15ba19489ef17358b78e1abdfd4a94234
