### ISSUE TITLE
Melhoria ferramenta de inspeção de feições

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#203]
Adicionar no combo box de escolha de camada o valor "Selecionar camada", de modo que o operador tenha que intencionalmente selecionar a camada que deseja utilizar.

Isso é devido ao uso de atalhos para "Inspecionar anterior" e "Inspecionar próximo", que mesmo quando o operador não está utilizando a ferramente, se ele acidentalmente pressionar o botão do atalho a ferramente navega na primeira camada em ordem alfabética.

**Comment by phborba** [comment]
No widget q usamos, a possibilidade de ter um item do combo não preenchido vai ser adicionada no qgis 3.0. Restringir o uso do atalho somente com a ferramenta ativada (inspetor aberto) resolveria o problema?

**Comment by dinizime** [comment]
Resolveria.

**Comment by phborba** [comment]
Resolvido no commit d49a28ed294c6386457f0c9ff2dac9af204e1809 .
