### ISSUE TITLE
Melhoria: Alterar o log de validação

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#205]
Atualmente cada mudança de estado na validação gera uma nova entrada na tabela de log. Seria interessante encapsular toda a execução em somente uma entrada no log.

Esse ticket é uma melhoria solicitada no issue #177

**Comment by jpesperidiao** [comment]
Feito no commit [c249b97](https://github.com/dsgoficial/DsgTools/commit/c249b97a7a83667f0884dcb486ed19cc672bbace) no branch [3.2_dev_ValidationToolbox_HistoryInfo_#177](https://github.com/dsgoficial/DsgTools/tree/3.2_dev_ValidationToolbox_HistoryInfo_%23177).

O #73 também está nesse commit.

Se puder testar, @phborba .

**Comment by jpesperidiao** [comment]
Ah, a janela do histórico agora fecha no `Esc` ,semelhante o comportamento de outras janelas.

**Comment by phborba** [comment]
Resolvido.
