### ISSUE TITLE
Método para verificar continuidade de atributos de feições lineares da mesma classe

### ISSUE THREAD

**Issue by rsmaior** [dsgoficial/DsgTools#208]
### Subject of the issue (Assunto do problema)
Ter uma ferramenta para verificar a continuidade de atributos de feições conectadas em casos específicos (trechos de drenagem com nomes escritos em caixa alta vs minúsculo por exemplo).

### Your environment (Seu ambiente)
Ubuntu Linux 64 bits
QGIS 2.18.13
DSGTools branch 3.1_dev 

### Expected behaviour (Comportamento esperado)
Subir uma flag quando houver 2 feições lineares da mesma classe conectadas porém com atributos diferentes. No caso de existirem 3 ou mais feições conectadas, fica a dúvida se é o caso ou não.

**Comment by dinizime** [comment]
Estamos implementando um protótipo, e assim que tiver uso comprovado em produção podemos verificar a migração para o DSGTools.

**Comment by dinizime** [comment]
Sendo testado em produção

**Comment by dinizime** [comment]
"Identifica mudança de atributos em linhas" do ferramentas experimentais

**Comment by phborba** [comment]
Portado do ferramentas experimentais pelo @pedro-mar no commit 11886b10b1516d34fa4515f8600fbbba2521ec0e
