### ISSUE TITLE
Melhoria: melhorar filtro de flags

### ISSUE THREAD

**Issue by jpesperidiao** [dsgoficial/DsgTools#209]
### Subject of the issue (Assunto do problema)
No momento, deve-se escolher se se quer filtrar as _flags_  por processo __ou__ por classe. Permitir ao usuário que a lista possa ser filtrada pelos dois (e.g. filtrar flags da camada "hid_trecho_drenagem_l" identificadas no processo "identifyDangles").

### Expected behaviour (Comportamento esperado)
Trocar o botão de escolha `Nome do processo`/`Nome da classe` por outro combobox editável.

**Comment by jpesperidiao** [comment]
Feito no commit [e2240b0](https://github.com/dsgoficial/DsgTools/commit/e2240b0ff888a49cf97956a6172679e9ffb4cd9e) do branch [3.2_dev_ValidationToolBox_#209](https://github.com/dsgoficial/DsgTools/tree/3.2_dev_ValidationToolBox_%23209).

**Comment by phborba** [comment]
Acabei de testar e seguem algumas observações:

* A lista só é filtrada quando os dois combos mudam, seria interessante que fosse atualizado com apenas a mudança de um;
* Seria interessante ter um texto no combo indicando o que ele significa, atualmente está vazio.

**Comment by phborba** [comment]
Resolvido. Fechando o ticket.
