### ISSUE TITLE
Nova Funcionalidade: Guardar estado do DSGTools no projeto

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#216]
Deseja-se guardar as interfaces abertas no momento em que o usuário salva o projeto.

- [ ] Docks abertos
- [ ] Parâmetros preenchidos na interface no momento (conexão de banco, botões criados, etc)

**Comment by jpesperidiao** [comment]
Para a implementação de estados, algumas medidas de padronização serão adotadas. A seguir, segue as sugestões de implementações.

### 1. Atualização dos gestores de ferramentas

Para que as ferramentas sejam acessíveis pelo gestor de estado, sugere-se a atualização de código dos `managers` segundo o padrão de _design **singleton**_.

### 2. Atualização e padronização de métodos de estados nas ferramentas

Propõe-se que todas as ferramentas que possam ter seu estado salvo tenho um atributo `PROJECT_STATE_VAR` que armazenará o nome da variável associado ao estado da ferramenta no escopo do projeto do QGIS.

Como a responsabilidade de informar seus atributos é da ferramenta, padroniza-se como métodos obrigatórios das ferramentas a ter seu estado implementado, conforme os métodos abaixo descritos.

Nome do método | Descrição | Argumentos de entrada | Saída do método
:---------:|----------------------------------|----------------------------------|------------------
`state` | Lê o estado atual da ferramenta | Não há | (dict) mapa de valores dos atributos que representam o estado da ferramenta
`setState` | Define o estado atual da ferramenta | (dict) mapa de valores dos atributos que representam o estado da ferramenta | (bool) indicativo de sucesso
`stateAsString` | Apresenta o estado de uma ferramenta sob a forma de texto de modo, garantindo sua serialização | (dict) mapa de valores dos atributos que representam o estado da ferramenta | (str) mapa de valores dos atributos que representam o estado da ferramenta sob a forma de _string_
`stateFromString` | Lê uma string e a converte à forma de mapa de valores | (str) estado da ferramenta sob a forma de texto | (dict) mapa de valores dos atributos que representam o estado da ferramenta
`validateState` | Avalia se a estrutura do mapa de valores é coerente com a definição de estado da ferramenta | (dict) estado da ferramenta a ser verificado | (bool) indicativo de validade do mapa apresentado


### 3. Gerenciamento de estado

Criação de um gestor de estados das ferramentas do DSGTools (`stateManager`).

Nome do método | Descrição | Argumentos de entrada | Saída do método
:---------:|----------------------------------|----------------------------------|------------------
`toolState` | Lê o estado atual de uma ferramenta | (str) tool: nome da ferramenta a ter seu estado lido | (bool) indicativo de sucesso
`setToolState` | Define o estado atual de uma ferramenta | (str) tool: nome da ferramenta a ter seu estado definido</br>(dict) state: mapa de valores dos atributos que definem o estado da ferramenta | (bool) indicativo de sucesso
`storedToolState` | Lê o estado de uma ferramenta que esteja salva no projeto do QGIS atual, se houver | (str) tool: nome da ferramenta a ter seu estado identificado | (dict) estado da ferramenta conforme salvo no atual projeto do QGIS
`saveToolState` | Salva o estado atual de uma ferramenta no projeto ativo do QGIS | (str) tool: nome da ferramenta a ter seu estado salvo</br>(dict) state: mapa de valores dos atributos que definem o estado da ferramenta | (bool) indicativo de sucesso
`loadToolState` | Lê o estado de uma ferramenta do projeto ativo do QGIS e o define à ferramenta | (str) tool: nome da ferramenta a ter seu estado carregado | (bool) indicativo de sucesso
`saveState` | Salva o estado de todas as ferramentas do DSGTools (que possuam suporte) | Não há | (bool) indicativo de sucesso
`loadState` | Carrega o estado de todas as ferramentas do DSGTools (que possuam suporte) | (dict) mapa dos nomes das ferramentas aos seus estados a ser definidos | (bool) indicativo de sucesso
`state` | Lê o estado atual de todas as ferramentas do DSGTools (que possuam suporte) | Não há | (dict) mapa de valores do nome da ferramenta ao seu estado atual
`savedState` | Lê o estado atual de todas as ferramentas do DSGTools (que possuam suporte) conforme salvo no projeto atual do QGIS | Não há | (dict) mapa de valores do nome da ferramenta ao seu estado salvo no projeto atual do QGIS

**Comment by phborba** [comment]
Feito no pull request #779 .
