### ISSUE TITLE
Adicionar possibilidade de Reshape na ferramenta de mão livre

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#233]
A ferramenta de mão livre somente pode ser utilizada para adicionar novos vetores. Seria interessante também ter a opção de utilizar o reshape com a ferramenta de mão livre.

Poderia ser utilizado o seguinte critério para escolha entre Reshape e Aquisição:
- Se existir uma e somente uma feição selecionada na camada ativa a ferramente se comporta no modo reshape, caso o contrário Aquisição. Poderia também trocar o ponteiro do mouse.

**Comment by phborba** [comment]
Feito no pull request #298 pelo @piangers . @jpesperidiao analisa as mudanças e faz o merge por favor ok?
