### ISSUE TITLE
 Conjunto de necessidade específicas de validação

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#236]
- Validar geometria curvas de nível: Curvas de diferentes cotas não podem se tocar (exceto em barragem e escarpa), Curvas de nível devem ser fechadas, tocar a moldura, ou tocar uma curva de nível de mesma cota.

- Validação de coerência de cotas de curva de nível e ponto cotado. O Gothic é capaz de apontar erros de preenchimento de cotas e curvas de nível.

- Relacionamentos espaciais complexos: Exemplo: Uma passagem em nível (P) deve estar na interseção entre um Trecho Ferroviario e um Trecho Rodoviario.
Uma ponte (P) deve estar na interseção entre um Trecho de Drenagem e um Trecho Rodoviario ou Trecho Ferroviario.
Caso um Trecho Rodoviario ou Ferroviario cruze uma Massa Dagua ou Trecho Massa dágua deve existir um elemento Ponte (L) coincidente com a interseção.

- Atributos com dependência espacial: O modalUso de Ponte deve ser Ferroviario se esta intersectar um Trecho Ferroviario.

**Comment by phborba** [comment]
@jpesperidiao esse ticket está no escopo do validador de regras espaciais. Acho que é o caso construir casos de unittest de cada um dos itens que o @dinizime levantou.

**Comment by jpesperidiao** [comment]
Acho que esse _isse_ separa em dois:

#460 e a utilização do Algoritmo de Regras Espaciais, já criado.

O que acham, @phborba e @dinizime, posso encerrar este?

**Comment by phborba** [comment]
Eu acho q podia fechar depois de criar os unittests citados, só pra exemplificar os novos casos que o validador de regras espaciais agora faz, o que você acha?

**Comment by dinizime** [comment]
Acho que o validador de regras espaciais não valida os seguintes casos:

Relacionamentos espaciais complexos: Exemplo: Uma passagem em nível (P) deve estar na interseção entre um Trecho Ferroviario e um Trecho Rodoviario.
Uma ponte (P) deve estar na interseção entre um Trecho de Drenagem e um Trecho Rodoviario ou Trecho Ferroviario.
Caso um Trecho Rodoviario ou Ferroviario cruze uma Massa Dagua ou Trecho Massa dágua deve existir um elemento Ponte (L) coincidente com a interseção.

Atributos com dependência espacial: O modalUso de Ponte deve ser Ferroviario se esta intersectar um Trecho Ferroviario.

**Comment by jpesperidiao** [comment]
@phborba tinha esquecido de ver os _unit tests_ do algoritmo de regras espaciais mesmo.

@dinizime esse eu acho que cobre usando o filtro espacial ('se ponte e modalUso é ferroviário, então deve sobrepor trecho ferroviário' junto 'pontes com modalUso diferente de ferroviário não sobrepõem trecho ferroviário'):  "Atributos com dependência espacial: O modalUso de Ponte deve ser Ferroviario se esta intersectar um Trecho Ferroviario.". O outro realmente acho que não é coberto.

**Comment by dinizime** [comment]
@jpesperidiao Concordo

**Comment by dinizime** [comment]
Com a definição dos requisitos para a validação esse tópico será reaberto em novas isses separadas por ferramenta.
