### ISSUE TITLE
 Conjunto de necessidade de modificação da ferramenta de classificação

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#237]
- Possibilidade de mudar ordem dos botões

- Editar a qual aba um botão pertence

- Busca textual criar uma aba nova com os botões em ordem alfabetica

- Considerar palavras chaves na busca (adicionar essa propriedade aos botões)

- Caso esteja em modo de reclassificação a busca textual também considera a geometria da feição que está selecionada.

- Easter egg de usar variáveis de projeto como entrada textual

- Selecionar a ferramenta que o botão vai chamar (circulo, angulo reto, free hand, normal)

- Selecionar se é para abrir ou não o form durante o modo aquisicão ou reclassificação.

- Método de atalho dinâmico (tick de usar atalhos dinâmicos). Somente atalhar aba ativa.
Atalha ou dinamico ou customisado

- Reclassificar multiplas feições - Utilizar o metodo do jossan. No futuro pensar sobre integrar com o custom form geral com filtro / pintar etc.

- Abas personalizadas
https://github.com/dsgoficial/DsgTools/issues/55

**Comment by jpesperidiao** [comment]
Resolvido na refatoração da Ferramenta de Classificação #496.

* Possibilidade de mudar ordem dos botões

> Adicionado o comportamento de alterar a ordem dos botões na interface de configuração do conjunto de botões ("Button setup")

* Editar a qual aba um botão pertence

> Adicionado o conceito de "grupo", que é genérico (sugestão para depois: adicionar um valor default que se baseia no nosso nome padrão de classes, de modo a simplificar o trabalho de criação).
Busca textual criar uma aba nova com os botões em ordem alfabetica

* Considerar palavras chaves na busca (adicionar essa propriedade aos botões)

> adicionado o conceito de palavras-chave.

* Caso esteja em modo de reclassificação a busca textual também considera a geometria da feição que está selecionada.

> Chegou-se à conclusão que isto pode confundir o usuário dada a forma como a busca está agora.

* Easter egg de usar variáveis de projeto como entrada textual

> o estado da caixa de ferramentas é salvo no projeto por meio de variável de projeto, podendo ser modificada durante o uso, ou por outras aplicações como o SAP. Há a previsão de _entry point_ utilizando a própria API do DSGTools de modo a simplificar esta manipulação [comentário no _issue_ 216](https://github.com/dsgoficial/DsgTools/issues/216#issuecomment-658970589).

* Selecionar a ferramenta que o botão vai chamar (circulo, angulo reto, free hand, normal)

> adicionado a possibilidade de seleção de ferramenta de aquisição.

* Selecionar se é para abrir ou não o form durante o modo aquisicão ou reclassificação.

> mantido o comportamento da ferramenta anterior, que permite a escolha de abertura (ou não) do formulário de feições.

* Método de atalho dinâmico (tick de usar atalhos dinâmicos). Somente atalhar aba ativa. Atalha ou dinamico ou customisado

> adicionado o conceito de atalho dinâmico (há a sugestão de colorização dinâmica de acordo com a primitiva geométrica da classe do botão).

* Reclassificar multiplas feições - Utilizar o metodo do jossan. No futuro pensar sobre integrar com o custom form geral com filtro / pintar etc.

> adicionado formulário próprio para reclassificação de múltiplas feições (inclusive de múltiplas camadas).

* Abas personalizadas

> entra no conceito de "grupo" dos botões.
