### ISSUE TITLE
Nova Funcionalidade: Ferramenta de Inversão de Linhas

### ISSUE THREAD

**Issue by jpesperidiao** [dsgoficial/DsgTools#239]
### Subject of the issue (Assunto do problema)

* Criar uma ferramenta para a inversão de linhas (ou um conjunto de linhas); e
* iniciar a criação do Processo de Validação de Fluxo de Linhas

### Expected behaviour (Comportamento esperado)

Inverter a linha selecionada (ou um conjunto de linhas).

**Comment by phborba** [comment]
Não seria melhor Flip Lines Tool? A operação tradicional é flip lines

**Comment by jpesperidiao** [comment]
Feito no commit [2253760](https://github.com/dsgoficial/DsgTools/commit/22537606d1d7700b2ca174d99791c6f691f2204f) do branch [3.2_dev_FlippingLineTool_#239](https://github.com/dsgoficial/DsgTools/tree/3.2_dev_FlippingLineTool_%23239).
