### ISSUE TITLE
Melhoria: Agrupar por camadas (selecionadas/não selecionadas) as feições no menu de contexto da Ferramenta de Seleção Genérica

### ISSUE THREAD

**Issue by jpesperidiao** [dsgoficial/DsgTools#240]
### Subject of the issue (Assunto do problema)
No menu de contexto da `Ferramenta de Seleção Genérica`, agrupar os elementos por camadas ao invés de exibir todos de uma vez, como é atualmente (semelhante ao comportamento da ferramenta `Identificar feições` do QGIS).

**Comment by jpesperidiao** [comment]
Feito no commit [0da8769](https://github.com/dsgoficial/DsgTools/pull/263/commits/0da8769f1b8ebca1a0bbf21f404cc9c30fdf73af).

**Comment by phborba** [comment]
merge feito.
