### ISSUE TITLE
Novo processo de validação: Direcionar rios

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#247]
Direcionar rios com base nos pontos de rede criados;

1. Criar pontos e classificar;
2. Encontrar trechos rio acima e rio abaixo;
3. Executar o direcionamento;
4. Caso apareçam flags do procedimento 3, corrigi-las e repetir o processo 3.

**Comment by jpesperidiao** [comment]
Processo de direcionamento baseado em tipos de nó da rede feitos no commit [a7acb01](https://github.com/dsgoficial/DsgTools/commit/a7acb018dd24bbd8d415d37c94bfdd8e6fc284f6) do branch [3.2_dev_ValidationProcess_%23103](https://github.com/dsgoficial/DsgTools/tree/3.2_dev_ValidationProcess_#103).

**Comment by jpesperidiao** [comment]
Falha minha: FUNCIONALIDADE concluída. Processo em progresso ainda.

**Comment by jpesperidiao** [comment]
Parâmetros do método:

- `Select All Valid Lines`: indica se ao final do processo as linhas que foram consideradas válidas serão selecionadas;
- `Classify Nodes On Database`: indica se, caso já exista uma tabela de nós no banco, deverá ser feita a reclassificação dos nós em banco;
- `Select Reference Layer`: camada de referência do banco (normalmente é a moldura);
- `Search Radius`: distância considerada para a classificação dos nós quanto ao posicionamento espacial relativo às camadas de comparação (moldura e camadas de corpo d'água);
- `Network Layer`: camada da rede [de hidrografia] a ser direcionada;
- `Only Selected`: orientar somente as feições da rede selecionadas (**tem que ter** um nó de inicío de trecho, senão o processo não irá varrer a rede); e
- `Sink Layer`: camada que contém os _sumidouros_ e _vertedouros_ da rede.

Sobre o uso:
O ideal é que a classificação de nós (opção `Classify Nodes On Database`) da rede só seja executada duas vezes: na primeira e na última, após não haver mais erros apontados pelo processo. Isto porque um dos passos da validação é justamente o de coerência de fluxo com tipo de nó em banco (pode ser que o operador, inadvertidamente, altere uma linha conectada a um ponto de moldura, por exemplo). Lembrando que, a princípio, o método é recursivo e deve ser repetido após cada conserto dos trechos indicados como _flags_.

**Comment by jpesperidiao** [comment]
Podem testar, @phborba , @lcoandrade e @felferrari ?
