### ISSUE TITLE
Migração das Ferramentas de Criação de Banco de Dados

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#260]
- [x] Migrar Criação de Postgis;
- [x] Migrar Criação de Spatialite;
- [x] Migrar Criação em lote.

**Comment by jpesperidiao** [comment]
Feito no branch [qgis3.0_migration_#260](https://github.com/dsgoficial/DsgTools/tree/qgis3.0_migration_%23260).

**Comment by phborba** [comment]
issue #90 foi feito juntamente com esse ticket
