### ISSUE TITLE
Bug na verificação de regras espaciais

### ISSUE THREAD

**Issue by RafaelAndradeS** [dsgoficial/DsgTools#262]
### Subject of the issue (Assunto do problema)
Describe your issue here. (Descreva seu problema aqui).

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Windows
* version of QGIS (Versão do QGIS): 2.18.17
* version of DSGTools (Versão do DSGTools): 3.1.2

### Steps to reproduce (Passos para reproduzir)
Tell us how to reproduce this issue. Please provide screenshots to further information. (Descreva os passos para reproduzir o problema. Por favor informe capturas de tela para informaçes adicionais)

Rodar Verificador de Regras Espaciais

### Expected behaviour (Comportamento esperado)
Tell us what should happen. (Nos informe o que deveria acontecer.)

Levantar flags

### Actual behaviour (Comportamento atual)
Tell us what happens instead. (Nos informe o que acontece ao executar o procedimento descrito.)

2018-04-27T15:58:08	2	'NoneType' object has no attribute 'setFocus'

**Comment by jpesperidiao** [comment]
Já foi resolvido para a versão 3.2.
