### ISSUE TITLE
Possibilidade de uso incorreto das ferramentas de angulo reto e mão livre

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#268]
### Subject of the issue (Assunto do problema)
É possivel ativar as ferramentas de mão livre, circulo, angulo reto e trocar de camada, causando resultados inesperados.
É desejavel que exista um reset nas ferramentas ao mudar a camada ativa.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional):  Windows 10
* version of QGIS (Versão do QGIS):  2.18.14
* version of DSGTools (Versão do DSGTools): 3.2_Dev

**Comment by phborba** [comment]
Resolvido no commit 026f798b104f46cbeaade5bbeca6de16ca2f7462
@dinizime testa pra mim por favor?

**Comment by dinizime** [comment]
Era interessante que todos os botões tivessem o mesmo comportamento do Freehand, ou seja, que ficasse desabilitados quando o edit está desligado.

**Comment by phborba** [comment]
Blz, vou acertar as outras tb.

**Comment by phborba** [comment]
Feito no commit 2de1661345e834e9260e802113fd10566d9e39c1
@dinizime testa pra mim por favor?
