### ISSUE TITLE
Dificil notar se o Icone do Dynamic histogram view está ativado ou não

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#269]
### Subject of the issue (Assunto do problema)
Seria interessante mudar o icone do botão 'Dynamic histogram view', pois é confuso ver se ele está ativado ou não.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional):  Windows 10
* version of QGIS (Versão do QGIS): 2.18.14
* version of DSGTools (Versão do DSGTools): 3.2_dev

**Comment by phborba** [comment]
Troquei lá, ficou melhor? @dinizime

**Comment by dinizime** [comment]
Ficou melhor!
