### ISSUE TITLE
Redimensionamento da janela e colunas do History

### ISSUE THREAD

**Issue by rsmaior** [dsgoficial/DsgTools#282]
### Subject of the issue (Assunto do problema)
1) O redimensionamento da janela do History verticalmente é livre, porém horizontalmente está limitado (só vai até aproximadamente metade da largura da minha tela de resolução 1680x1050).
2) Não é possível alterar a largura das colunas do History.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Kubuntu 16.04.4 LTS (Linux - 64 bits)
* version of QGIS (Versão do QGIS): 2.18.13
* version of DSGTools (Versão do DSGTools): 3.1.2

### Steps to reproduce (Passos para reproduzir)
1) Abra o History e vá redimensionando a janela aumentando cada vez mais a largura.
2) Abra o History e coloque o cursor entre duas colunas no cabeçalho da tabela. 

### Expected behaviour (Comportamento esperado)
1) Poder redimensionar horizontalmente de forma livre, assim como atualmente na direção vertical.
2) Mundança do ícone do mouse de seta para o ícone de redimensionamento e a ativação do redimensionamento lateral das colunas na região do cabeçalho.

### Actual behaviour (Comportamento atual)
1) O redimensionamento horizontal da janela acontece até um certo ponto, em que então não será mais possível alargar a janela (aproximadamente metade da largura tela).
2) Não é possível redimensionar a largura das colunas e não há alteração no ícone do mouse.

**Comment by phborba** [comment]
Esse ticket não tem mais relevância, dado que não existe mais essa interface no DSGTools 4.0.
