### ISSUE TITLE
Dissolver areas e merge lines com uma blacklist default

### ISSUE THREAD

**Issue by rsmaior** [dsgoficial/DsgTools#283]
### Subject of the issue (Assunto do problema)
Atualmente os processos de Dissolve Area with common atributes e Merge Lines with common atributes exigem que seja acrescentada uma lista com os atributos a serem ignorados. Porém, acho que é mais interessante já ter uma lista por padrão e se for o caso basta apagar da lista algum atributo.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Kubuntu Linux 16.0.4 (64 bits)
* version of QGIS (Versão do QGIS): 2.18.13
* version of DSGTools (Versão do DSGTools): 3.1.2

### Steps to reproduce (Passos para reproduzir)
Rodar um dos processos mencionados e observar que não há valores por padrão.

### Expected behaviour (Comportamento esperado)
1) Dissolve Area with common atributes: 
A blacklist editável ser inicializada com os seguintes valores por padrão **id,observacao,data_modificacao,controle_id,ultimo_usuario,area_otf**
2) Merge Lines with common atributes: 
A blacklist editável ser inicializada com os seguintes valores por padrão 
**id,observacao,data_modificacao,controle_id,ultimo_usuario,length_otf**

### Actual behaviour (Comportamento atual)
É necessário criar a blacklist do zero para os dois processos.

**Comment by phborba** [comment]
Não sei se isso procede, pois só nossos bancos tem esses campos. Além disso, não é preciso colocar o id na blacklist (os campos da pk já são ignorados). Idem para length_otf.
