### ISSUE TITLE
funcionalidades only selected e desagregar internos do Dissolve não funcionam

### ISSUE THREAD

**Issue by rsmaior** [dsgoficial/DsgTools#284]
### Subject of the issue (Assunto do problema)
O processo Dissolve polygons with common atributes não está realizando por feições selecionadas e também o deaggregate "interno" dele (que roda ao fim dele) não está desagregando as geometrias.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Kubuntu Linux 16.04.4 (64 bits)
* version of QGIS (Versão do QGIS): 2.18.13
* version of DSGTools (Versão do DSGTools): 3.2_dev

### Steps to reproduce (Passos para reproduzir)
Iniciar o processo Dissolve com o parâmetro apenas feições selecionadas marcado.

### Expected behaviour (Comportamento esperado)
O processo Dissolve deveria:
1) Rodar apenas nas feições selecionadas; e
2) Desagregar as geometrias ao fim do processo.

### Actual behaviour (Comportamento atual)
O processo Dissolve está:
1) Rodando em todas as feições da camada; e
2) Não está desagregando as geometrias ao fim do processo.

**Comment by phborba** [comment]
Resolvido na migração.
