### ISSUE TITLE
Uso da ferramenta de forçar validade de geometria

### ISSUE THREAD

**Issue by Lucas3ls** [dsgoficial/DsgTools#296]
-Na utilização da ferramenta de forçar validade de geometrias ela acusou um erro e abortou o processo.
 Erro: "_Problem Creating temp table cb.loc_aglomerado_rural_isolado_p: ERROR: parameter $1 of type 
 integer cannot be coerced to the expected type uuid.
 HINT: You will need to rewrite or cast the expression._"
-Estou usando o Windows 10, QGIS 2.18.20, DSGTools 3.2

**Comment by phborba** [comment]
Existe uma forma de burlar esse erro momentaneamente, que seria trocar o tipo do id da tabela cb.loc_aglomerado_rural_isolado_p . Vocês estão usando o banco antigo do dsgtools, no qual essas tabelas de localidade tinham id do tipo UUID, que causa problema na forma de criar as tabelas temporárias da validação. Enquanto não verificamos uma alternativa, você pode fazer o que eu sugeri para não atrasar seu trabalho.

**Comment by phborba** [comment]
@Lucas3ls  me manda por email um dump do banco que você está tendo problema, por favor, pois não estou conseguindo reproduzir aqui, dado que meus dados já estão no formato novo.

**Comment by Lucas3ls** [comment]
Beleza, estamos usando um banco antigo do DSGTools mesmo. Mandei o dump pro seu email.

**Comment by jpesperidiao** [comment]
Na nova versão do DSGTools esse problema não ocorre mais, porém não haverá _backport_ para o DSGTools 3.2.
