### ISSUE TITLE
Bug com sinais da Ferramenta de Aquisição a Mão Livre

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#297]
### Subject of the issue (Assunto do problema)
Problemas com travamento ao salvar reportado da versão nova do DSGTools. Foi verificado que o travamento ocorre com sinais da Free Hand e que o mesmo passou a não ocorrer mais quando a inserção da ferramenta foi comentada no dsg_tools.py

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Windows 7
* version of QGIS (Versão do QGIS): 2.18.19
* version of DSGTools (Versão do DSGTools): 3.2

### Steps to reproduce (Passos para reproduzir)
Adquirir feições, trocar de camadas e de ferramentas e depois tentar salvar.

### Expected behaviour (Comportamento esperado)
Não deveria ocorrer travamento, dado que há um número pequeno de feições a ser salvo.

### Actual behaviour (Comportamento atual)
Travamentos de mais de 1 minuto antes de salvar.

**Comment by phborba** [comment]
@jpesperidiao esse foi resolvido?

**Comment by jpesperidiao** [comment]
Creio que sim, junto com a migração dos sinais para o manager (#307). Fiz alguns teste aqui e não percebi problemas.
