### ISSUE TITLE
Levantamento de Requisitos para Integração SAP - DSGTools

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#309]
Documentação dos requisitos para integração do SAP com o DSGTools
O DSGTools deve ser capaz de:

1. Carregar camadas com parâmetros definidos pelo SAP;
2. Carregar regras de atributação para tabela de atributos e formulário de feições;
3. Aplicar configurações externas definidas pelo SAP;
4. Definir menus específicos de aquisição (evolução da ferramenta de classificação);
5. Adequar o menu de aquisição;
6. Processo que identifica problemas de atributação em camadas;
7. Definir workflow externamente;
## 1. Carregar camadas com parâmetros definidos pelo SAP;
Parâmetros:
- [ ] Filtro (atributo e/ou espacial);
- [ ] Formulário custom;
- [ ] Estilo;
- [ ] Variável de camada;

**Comment by dinizime** [comment]
Foi criado o branch dev_sapIntegration para modificar processings de forma a garantir a integração com o SAP.

No momento ainda falta a integração com o Menu de Classificação
