### ISSUE TITLE
Atualizar conteúdo do help para a versão 4.0

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#320]
- [x] Criar pdf do antigo e armazenar
- [x] Atualizar seções do help online

**Comment by phborba** [comment]
Pendências:
- [ ] Referências bibliográficas;
- [ ] Revisar o texto para retirar frases que não fazem mais sentido. Como exemplo: O sistema de gerenciamento de permissões do DsgTools evoluiu na versão 3.0, ficando mais amigável ao usuário. Vejamos as diferenças implementadas. A figura 9 mostra a situação inicial da aba de permissões. (pág 10 do manual);
- [ ] Adicionar imagens explicativas nos processos de validação (melhoria, não é impeditivo para o lançamento);
- [ ] Adicionar descrições dos tipos de processos;
- [ ] Atualizar nomes dos processos renomeados;

@jpesperidiao vê isso pra mim por favor.

**Comment by jpesperidiao** [comment]
@phborba:

- tem que revisar a parte de processos (verificar se as definições e descrições estão adequadas);
- adicionar/atualizar imagens descritivas; e
- (é do _changelog_, mas enfim) criar _gif_ caso queira.

**Comment by phborba** [comment]
@jpesperidiao temos que atualizar algumas coisas (documentação e changelog)

- [ ] QA Toolbox;
- [ ] QA Toolbar;
- [ ] Unittests;
- [ ] Novos processos da processing toolbox (Carrega, Grid, novos processos de validação);
