### ISSUE TITLE
Problemas modelagem 2.1.3

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#323]
- Falta o atributo largura em Tunel
- Falta o atributo geometriaaproximada em Trecho_Massa_Dagua
- Falta o atributo geometriaaproximada em Rocha_Em_Agua
- Falta o atributo geometriaaproximada em Galeria_Bueiro
- Falta o atributo capacCarga em Trecho_Rodoviario
- Falta o atributo alturamediaindividuos em Mangue
- Falta o atributo alturamediaindividuos em Cerrado_Cerradao
- Falta o atributo nomeabrev em Nome_Local
- O atributo ndutos em trecho_duto deveria ser nrdutos
- O atributo ndutos em condutor_hidrico deveria ser nrdutos
- o atributo vaolivrevertical em ponte deveria ser vaovertical
- O atributo areaoficialha deveria ser areaoficial em Unidade_Uso_Sustentavel (e ser do tipo varchar)
- Não deveria existir os atributos nome e nomeabrev para Ponto_Drenagem
- Não deveria existir o atributo geocodigo para Cidade, Vila e Localidade
- Não sei se faz sentido o atributo geometriaaproximada nas classes de descontinuidade
- Para algumas categorias descontinuidade não possui as 3 primitivas geométricas. Por exemplo, para ADM só possui ponto e área.
- Os atributos nome de foz_maritima, nome de massa_dagua, nome de quebramar_molhe, periodicidadeinunda de terreno_suj_inundacao, e nome de trecho de drenagem estão com tipo character em vez de character varying
- Existe um grupo de atributos com tipo double precision (por exemplo cota em ponto cotado) e um grupo de atributos com tipo real (por exemplo altura em queda dagua). Não sei se tal escolha é intencional.

- A classe loc_aglomerado_rural_p deveria ser Não instanciável. O melhor seria deixar sem "_p" no final para indicar isso.
- A classe pto_pto_geod_topo_controle_p deveria ser Não instanciável. O melhor seria deixar sem "_p" no final para indicar isso.
- As classes lim_area_especial_a e lim_area_especial_p deveriam ser Não instanciável. O melhor seria deixar sem "_p" e "_a" no final para indicar isso.
- A classe lim_area_politico_adm_a deveria ser Não instanciável. O melhor seria deixar sem "_a" no final para indicar isso.
- A classe aux_descontinuidade_geometrica deveria ser Não instanciável. O melhor seria deixar sem "_a" "_p" e "_l" no final para indicar isso.
- A classe loc_localidade_p deveria ser Não instanciável. O melhor seria deixar sem "_p" no final para indicar isso.
- A classe veg_vegetacao_a deveria ser Não instanciável. O melhor seria deixar sem "_a" no final para indicar isso.

**Comment by dinizime** [comment]
- Deposito_Geral não deveria possuir tipodepgeral 19 Reservatório de combustível
- Ext_Mineral não deveria possuir os codelist 43 Saibro e 44 Piçarra, deveria ser somente 43 Saibro/Piçarra
- Edif_Energia não deveria ter o matconstr 97 Não aplicável
- Hidrelétrica não deveria ter tipoestgerad 0 Desconhecido, 5 Eólica, 6 Solar, 7 Maré Motriz
- Termelétrica não deveria ter tipoestgerad 0 Desconhecido, 5 Eólica, 6 Solar, 7 Maré Motriz
- Natureza_Fundo não deveria ter materialpredominante 97 Não aplicável
- Unidade Federação acho que não faz sentido ter sigla 0 Desconhecido. (Na verdade esse campo é varchar segundo a EDGV, mas faz sentido utilizar um codelist para padronizar)

**Comment by phborba** [comment]
Resolvidos na nova implementação da 2.1.3
