### ISSUE TITLE
Bugs na migração pro QGIS3

### ISSUE THREAD

**Issue by elitonfilho** [dsgoficial/DsgTools#324]
Divisão basead nos itens da aba DSGTools (em negrito)

**Manage database from server**
* Após realizar movimentações das databases entre os boxs da esquerda e da direita, o QGIS solicitou credenciais para conectar nos db template_xxx, gerando às vezes KeyError: 'Load Database Model EDGV Version 3.0 Pro'
* Ao selecionar a opção Load Database Model EDGV Version 3.0 Pro gera KeyError: 'Load Database Model EDGV Version 3.0 Pro'
* Após realizar movimentações das opções de database em alguma ordem específica ocorre duplicação de db na caixa de seleção
* Na opção Drop Databses, a janela de confirmação do drop mostra o seguinte texto: 'Do you really want to drop databases: template_edge_213, template_edgv_fter_2a_ed, template_edgv3, database_teste', onde database_teste era a única db selecionada para o drop.
* Mesmo gerando uma box de “Please select one or more databases to drop!” ao tentar dropar uma db sem nenhuma selecionada, uma box que confirma o drop é gerada.
*Ao utilizar o botão update PostGIS version,o plugin tenta a conexão nas db template_xxx e depois gera uma box com: 'Upgrade Posgtis operation complete. Successful databases: database_testeError for database template_edgv_3'
* Ao utilizar o botão Run SQL from file, ele tenta conectar nas db template_xxx. Mesmo fechando a janela de selecão da SQL, uma box é gerada com: Customize from SQL file operation complete.
Error for database template_edgv_3
* Na aba Style Management, os botões Import e Delete Styles geram AttributeError: 'NoneType' object has no attribute 'db'
* Reiniciando o QGIS e indo diretamente ao botáo Delete Style (i.e. não testando outros botões antes) gera o erro AttributeError: 'SelectStyles' object has no attribute 'selectedStyles' após cancelar a operação.
* Logo após, ao tentar importar um estilo, gera o erro KeyError: 'EDGV 2.1.3 Pro'
* Ao tentar deletar apenas um estilo a ferramenta acaba deletando todos, gerando a seguinte box após a operação: 'Delete operation complete. Successful databases: database_teste,database_teste,database_teste...(uma entrada para cada estilo no banco)
* Na aba permissions: Pressionando o botoão Import e cancelando a operação gera uma box com a mensagem: Error! Problem importing permission: expected str, bytes or os.PathLike object, not tuple. Realizando o mesmo processo no botao batch import gera uma box com Error! Select a input folder!
* Em Server Permissions Editor não é possivel setar o Sistema de Coordenadas
* Nas abas Earth Coverage e Field Box Configuration: geram uma box de Install Field Toolbox configuration complete (ou Uninstall Field Toolbox configuration complete.) mesmo após abortando o processo

**Database Tools**
* Em Create a PostGIS or a SpatialLite database, caso selecionarmos 'Create a new server' temos o seguinte erro: Error opening database: fe_sendauth: no password supplied QPSQL: Unable to connect
* Erro em Create database from template : AttributeError: 'ConnectionComboBox' object has no attribute 'currentText' 
* Obs: Após falha ao criar uma db PostGIS, uma janela sugere visualizar o log, mas não informa onde o mesmo está. Seria interessante indicar seu path
* Obs: Seria interessante, na seção de Create a PostGIS or Spatialite database, indicar quais caracteres não são aceitos na criação da database. Inserção de caracteres especiais resulta em erro na criação da db.

**Layer Tools**
* Ao tentar criar um frame criar um frame (Postgis e SLite) gera NameError: name 'QCursor' is not defined

**BDGEx**
* Obs: Verificar se a disponibilidade no BDGEx é condizente com o mostrado (ou seja, verificar se o wms está atualizado)
* Não há nada em Orthorectified True Color Imagery compatible with 1:25000

**Production Tools**
* Os processos de validação não aparecem no Toolbox do Plugin mas aparecem na Processing Toolbox do QGIS
* Em Reclassification Tools: Ao alternar entre New Feature Mode e Reclassify Feature Mode gera TypeError: decorated slot has no signature compatible with currentLayerChanged(QgsMapLayer*)
* No setup da Reclassification Tool, ao tentar remover um elemento clicando com o botao direito (Remove Child Node) gera AttributeError: 'NoneType' object has no attribute 'removeChild' 
* Ao utilizar um botão gerado temos: AttributeError: 'list' object has no attribute 'geometry', além de criar uma nova camada (duplicar) sempre que o botão for pressionado.
* Gerando um button com as seguintes características: classe aux_valida_p, alternando valores nos campos value, editable e ignored e selecionando os parametros de: open feature form e assign color, gera AttributeError: 'QgsVectorLayer' object has no attribute 'setFieldEditable' . Também duplica a camada.
* Após gerar o butão com alguma db selecionada: se trocarmos de db gera RuntimeError: wrapped C/C++ object of type QPushButton has been deleted
* Ao alternar entre as abas PostGIS e SpatialLite os parâmetros de conexão (logo abaixo das abas) ficam em branco
* Obs: Na Ferramenta de Right Degree Angle digitizing é possível fazer edificações com formatos malucos, mas acredito que seja difícil pegar esses casos. O mesmo acontece na free hand.
* Minimun area tool: No botão create custom size gera erro NameError: name 'QtGui' is not defined 
* Set Values from point: gera TypeError: QgsMessageBar.pushInfo(): 'duration' is not a valid keyword argument 

* Utilizando o tamanho de fonte 16 (settings do QGIS) a linha de butões do DSGTools na Label Toolbar aparenta ser maior que os outros botões do QGIS

**Testado no QGIS 3.4.4 utilizando o branch qgis3.0_migration**

**Comment by phborba** [comment]
Eliton, muito obrigado pelo feedback. Passei para o @jpesperidiao  a correção dos bugs.

Um abraço!

**Comment by jpesperidiao** [comment]
Não estou conseguindo reproduzir "[...] Na opção Drop Databses, a janela de confirmação do drop mostra o seguinte texto: 'Do you really want to drop databases: template_edge_213, template_edgv_fter_2a_ed, template_edgv3, database_teste', onde database_teste era a única db selecionada para o drop.[...]".

@elitonfilho, informa o SO que tu usou (e o passo-a-passo), por favor!

**Comment by jpesperidiao** [comment]
Não entendi a parte "[...]Após realizar movimentações das databases entre os boxs da esquerda e da direita, o QGIS solicitou credenciais para conectar nos db template_xxx[...]".

Tu ficou colocando e removendo bancos da lista de bancos a serem gerenciados?

Consertei o "[...]gerando às vezes KeyError: 'Load Database Model EDGV Version 3.0 Pro'[...]".

Vê se isso resolve o problema como um todo (as soluções estão no branch [qgis3.0_migration_#325](https://github.com/dsgoficial/DsgTools/tree/qgis3.0_migration_%23325)).

**Comment by jpesperidiao** [comment]
Consertei os bugs informados conforme o #325, alguns eu não consegui reproduzir (talvez fossem eventos dependentes). Teria como tu verificar se estão sanados os problemas de `Manage database from server`, @elitonfilho ?

**Comment by elitonfilho** [comment]
> Não estou conseguindo reproduzir "[...] Na opção Drop Databses, a janela de confirmação do drop mostra o seguinte texto: 'Do you really want to drop databases: template_edge_213, template_edgv_fter_2a_ed, template_edgv3, database_teste', onde database_teste era a única db selecionada para o drop.[...]".
> 
> @elitonfilho, informa o SO que tu usou (e o passo-a-passo), por favor!

SO utilizado: W10 Version1 0.0.17134 Build 17134

Para chegar nesse passo realizei trocas dos bancos entre as caixas da esquerda e direita (Server Databases) e troca entre as abas logo abaixo da caixa de seleção.
![image](https://user-images.githubusercontent.com/37584879/52013361-fb9b6a80-24c3-11e9-8634-2beeb0759fa6.png)

**Comment by jpesperidiao** [comment]
E aí, @elitonfilho , conseguiu testar? A princípio TODAS as correções estão no branch [qgis3.0_migration_#325](https://github.com/dsgoficial/DsgTools/tree/qgis3.0_migration_%23325).

**Comment by elitonfilho** [comment]
Ainda não verifiquei @jpesperidiao , irei testar e te passar um feedback assim que possível

**Comment by elitonfilho** [comment]
Realizando os testes antigos pude verificar que todos os check do #325 foram resolvidos, com alguns outros bugs surgindo:
* Ao tentar importar um estilo (de uma db EDGV 3.0) gera: StopIteration 
* Leva muito tempo para carregar o setup da Reclassification Tools (mais de 30 seg no meu caso)
* Ao carregar um arquivo .reclass na Feature Classification Tool e ao tentar utilizar um botão de reclassificação gera AttributeError: 'NoneType' object has no attribute 'geometryType' (no modo reclassify feature) ou 'NoneType' object has no attribute 'editFormConfig'  (no modo new feature)

**Comment by jpesperidiao** [comment]
@elitonfilho,

se puder, faz o upload do arquivo `.reclass` pra que eu consiga testar com ele aqui.

* ```Ao tentar importar um estilo (de uma db EDGV 3.0) gera: StopIteration```: qual a versão do Python3 que tu tá usando?

**Comment by elitonfilho** [comment]
Segue o arquivo .reclass utilizado.  Foi gerado de maneira aleatória:

[teste.zip](https://github.com/dsgoficial/DsgTools/files/2871867/teste.zip)

A versão instalada no meu computador é a 3.7.2, mas isso influenciaria no QGIS? (já que o QGIS possui Python3.7.0 em sua pasta de instalação)

**Comment by phborba** [comment]
Abri um novo ticket com esses novos bugs. Vou fechar esse aqui.
