### ISSUE TITLE
Observações DSGTools 4

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#326]
Segue uma lista de observações:
- Remover criação de bancos seguindo a especificação da EDGV Fter. Acho que podemos considerar a especificação descontinuada

- No carregamento de camadas remover o filtro específico da EDGV FTer

- Espero enviar na semana do dia 11 fevereiro a SQL final da EDGV Pro e da EDGV 2.1.3 para substituição no DSGTools

- Ao selecionar um banco no Windows 10 duas telas do Prompt do Comando aparecem rapidamente.

- Após aplicar um filtro no Inspect Feature Tool ao clicar no Back inspect o seguinte erro python ocorre:
`Traceback (most recent call last):
  File "C:/Users/Diniz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DsgTools\gui\ProductionTools\Toolbars\InspectFeatures\inspectFeatures.py", line 144, in on_backInspectButton_clicked
    self.iterateFeature(method)
  File "C:/Users/Diniz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DsgTools\gui\ProductionTools\Toolbars\InspectFeatures\inspectFeatures.py", line 228, in iterateFeature
    id = featIdList[index]
IndexError: list index out of range`

- Conversão está estourando o limite de conexões com o banco (Banco postgres 2.1.3 para um novo banco postgres 2.1.3, strict conversion)

**Comment by dinizime** [comment]
O erro de list index out of range na Inspect Feature Tool ainda persiste.

Outro problema é que se aplicar um filtro, e depois quiser remove-lo o botão "OK" fica desabilitado, e é obrigatório preencher algo no filtro.

Ao utilizar a Inspect Feature Tool com Shapefile em todas as navegações aparece a mensagem "Selected id does not exist on layer XXX. Returned the previous id."

**Comment by phborba** [comment]
Resolvido no commit a75975ce569ba49d03658c5e99fe749689fed982
