### ISSUE TITLE
PostGIS: too many clients

### ISSUE THREAD

**Issue by jpesperidiao** [dsgoficial/DsgTools#328]
### Subject of the issue (Assunto do problema)
Diversas conexões são iniciadas e não encerradas, estourando o limite de conexões de alguns servidores, impedindo o uso de novas conexões.

O problema é notório ao se tentar realizar a conversão de um banco de dados antigo para um novo (que seria criado).

**Comment by phborba** [comment]
Testei o pull request #9107 do repositório do QGIS (compilei o QGIS dev) e esse fix não sanou nosso problema. Suspeito das camadas estarem sendo travadas pelo QMutex que rola nas dependent layers na implementação do QgsTask. Sugiro retirar do QgsTask para o lançamento e voltarmos a esse problema na próxima versão do DSGTools. O que acha @jpesperidiao ?

**Comment by phborba** [comment]
Solução paleativa dada no pull request #336 .
