### ISSUE TITLE
Problemas na Ferramenta de Classificação

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#335]
Problemas levantados pelo @elitonfilho no issue #324:
- [ ] Leva muito tempo para carregar o setup da Reclassification Tools (mais de 30 seg no meu caso)
- [x] Ao carregar um arquivo .reclass na Feature Classification Tool e ao tentar utilizar um botão de reclassificação gera AttributeError: 'NoneType' object has no attribute 'geometryType' (no modo reclassify feature) ou 'NoneType' object has no attribute 'editFormConfig'  (no modo new feature)

**Comment by jpesperidiao** [comment]
- `Leva muito tempo para carregar o setup da Reclassification Tools (mais de 30 seg no meu caso)`

Não consigo reproduzir. @elitonfilho, é sempre que fica lento?

- `Ao carregar um arquivo .reclass na Feature Classification Tool e ao tentar utilizar um botão de reclassificação gera AttributeError: 'NoneType' object has no attribute 'geometryType' (no modo reclassify feature) ou 'NoneType' object has no attribute 'editFormConfig'  (no modo new feature)`

Resolvido e já está no branch da 4.0 dev ([qgis3.0_migration](https://github.com/dsgoficial/DsgTools/tree/qgis3.0_migration)).
