### ISSUE TITLE
Bug Ferramenta ângulo reto

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#338]
* Snap não está funcionando com a ferramenta de ângulo reto.

* Parece que tem algum bug na restrição de aquisição da ferramenta de ângulo reto (não a de tamanho mínimo do vértice mas a que tenta calcular outras distâncias). Talvez essa restrição seja complicada demais e deve estar com algum bug.
Também é frustrante pro usuário pois ele não entende porque não consegue fechar a feição, já que não tem nenhum indicativo.

**Comment by dinizime** [comment]
![image](https://user-images.githubusercontent.com/10109704/53696448-d725fd00-3da5-11e9-9509-841662b6b77e.png)

Esse construção não respeita o tamanho mínimo configurado (testado com tamanho mínimo 4 e 10) sempre é possível fazer o ultimo lado menor que a tolerância.

**Comment by phborba** [comment]
O snap foi resolvido né?

**Comment by dinizime** [comment]
Resolvido o snap.
