### ISSUE TITLE
Bug Digitalização Mão livre Dsgtools 4

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#345]
Em alguns momentos a ferramenta de mão livre não adiciona feição (não subindo nenhum erro python). Apertar o ctrl repetidamente resolve o problema. Parece ser algum bug relacionado ao reshape do mão livre.

**Comment by dinizime** [comment]
Em novos testes a ferramenta não está seguindo as opções de suprimir formulário.

**Comment by jpesperidiao** [comment]
Depois de estudarmos um pouco o ocorrido, chegamos a conclusão de que a melhor solução seria separar os dois casos de uso (aquisição e reshape) em duas ferramentas: `Free Hand Acquisition` e `Free Hand Reshape`.

As alterações, a princípio, estão no branch [qgis3.0_migration_#345](https://github.com/dsgoficial/DsgTools/tree/qgis3.0_migration_%23345).

**Comment by jpesperidiao** [comment]
@dinizime, teria como verificar se a solução proposta resolve o problema?

Último commit foi o [2c1116e](https://github.com/dsgoficial/DsgTools/commit/2c1116e0528f3ba9cfe8ba1610e2ab8c483c7436).

**Comment by phborba** [comment]
@dinizime você pode testar por gentileza?
