### ISSUE TITLE
Implementar o EnviromentSetter

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#349]
É composto pelos seguintes passos:

- [ ] Carregar camadas usando o LayerLoader;
- [ ] Carregar estilos;
- [ ] Carregar camadas não espaciais referentes a simbologia (filtrando pelo produto);
- [ ] Realizar join das camadas com as camadas não espaciais de simbologia;
- [ ] Criar grid de edição;
- [ ] Preparar polígono invertido da moldura para edição;
- [ ] Ajustar ordem de visualização de camadas;

**Comment by dinizime** [comment]
Requisitos de edição vão ser repensados baseado no protótipo que está em fase de testes.
