### ISSUE TITLE
Adaptar o LayerLoader para carregar as tabelas auxiliares de edição

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#350]
Lembretes:
- [x] Carregar tabelas de posicionamento de simbologia;
- [ ] Após carregar tabela de posicionamento de simbologia, aplicar filtro de produto (filtro de camada);
- [x] Fazer o join com a camada original;

**Comment by dinizime** [comment]
Requisitos de edição vão ser repensados baseado no protótipo que está em fase de testes.
