### ISSUE TITLE
Processo de fix invalid geometry some feições

### ISSUE THREAD

**Issue by rsmaior** [dsgoficial/DsgTools#367]
### Subject of the issue (Assunto do problema)
Quando rodo o processo de identificar e validar geometria, algumas geometrias somem. Testei no QGIS 2.18 e a mesma geometria não some. Coloquei em anexo um shapefile exemplificando.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional):  Kubuntu 16.04 - 64 bits
* version of QGIS (Versão do QGIS): 3.4.3
* version of DSGTools (Versão do DSGTools): 4.0 do branch de migração para o QGIS3 (commit 562e15b2f4e9835c96771433baf4a5de49140bc3)

### Steps to reproduce (Passos para reproduzir)
Carregar o arquivo shapefile anexo no QGIS3. Escolher o processo de identificar e consertar geometria inválida. Verficar que uma das geometrias some.

### Expected behaviour (Comportamento esperado)
Consertar as geometrias inválidas sem eliminá-las. 

### Actual behaviour (Comportamento atual)
Uma das geometrias está sumindo. Ela é relativamente grande, então não é difícil de ver.

[floresta.zip](https://github.com/dsgoficial/DsgTools/files/2906920/floresta.zip)

**Comment by jpesperidiao** [comment]
@rsmaior, resolvido no commit [67673b3](https://github.com/dsgoficial/DsgTools/commit/67673b367b57521e05915bf17310b1a624c6545d). Já tá no brach qgis3.0_migration. Dá uma olhada lá!

**Comment by rsmaior** [comment]
Funcionando!
