### ISSUE TITLE
Configurações da ferramenta de aquisição mão livre

### ISSUE THREAD

**Issue by jossanCosta** [dsgoficial/DsgTools#379]
### Subject of the issue (Assunto do problema)
Erro ao definir configurações do mão livre.
![erro_free_hand](https://user-images.githubusercontent.com/20671795/53437394-2f42b500-39dc-11e9-8ada-19053ddd88a7.png)

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional):  Windows 10
* version of QGIS (Versão do QGIS): 3.4.5
* version of DSGTools (Versão do DSGTools): 4.0-DEV

### Steps to reproduce (Passos para reproduzir)
Após definir as configurações do mão livre e adquirir um feição com a ferramenta.

**Comment by phborba** [comment]
Fizemos os testes aqui e com número de iterações maior que 15, estoura memória e dá esse erro aí.

**Comment by jpesperidiao** [comment]
Como o @phborba falou, o número de iterações é relacionado com o consumo computacional. A solução dada foi indicar isto ao usuário.

**_Caveat_**: a geometria é mantida sem suavização.
