### ISSUE TITLE
Identificar e consertar geometrias inválidas não identifica nem remove geometria nula/vazia

### ISSUE THREAD

**Issue by rsmaior** [dsgoficial/DsgTools#382]
### Subject of the issue (Assunto do problema)
A rotina não está identificando nem removendo as geometrias de área nula

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Kubuntu 16.04 (versão 64 bits)
* version of QGIS (Versão do QGIS):  3.4.3
* version of DSGTools (Versão do DSGTools): 4.0 do branch de migração para o QGIS3 (commit 562e15b2f4e9835c96771433baf4a5de49140bc3)

### Steps to reproduce (Passos para reproduzir)
a. Com a oção consertar geometrias marcada: Rodar a rotina numa camada com feições de geometria nula, com a opção consertar geometrias marcada. Verificar na tabela de atributos que as geometrias nulas continuam na camada e também que não aparece no log do QGIS/Processing qualquer texto sobre essas geometrias;
b. Sem a oção consertar geometrias marcada: Rodar a rotina numa camada com feições de geometria nula, sem a opção consertar geometrias marcada. Verificar que não aparece no log do QGIS/Processing qualquer texto sobre essas geometrias.

### Expected behaviour (Comportamento esperado)
a. Com a oção consertar geometrias marcada: Deveria eliminar as geometrias nulas e depois reportar no log do QGIS/Processing;
b. Sem a oção consertar geometrias marcada: Deveria reportar as geometrias nulas no log do QGIS/Processing.

### Actual behaviour (Comportamento atual)
a. Com a oção consertar geometrias marcada: As geometrias nulas não são removidas e não sobem texto pro log do QGIS/Processing ;
b. Sem a oção consertar geometrias marcada: As geometrias nulas não sobem texto pro log do QGIS/Processing.

Obs: acrescentei um geopackage amostra com 5 geometrias não nulas e 2 nulas pra facilitar

[2_geometrias_vazias.gpkg.zip](https://github.com/dsgoficial/DsgTools/files/2937398/2_geometrias_vazias.gpkg.zip)

**Comment by phborba** [comment]
Geometria nulas e vazias não são geometrias inválidas segundo a OGC, logo não são tratadas nesse processo. Esse tipo é tratado no processo de remover geometrias nulas.
