### ISSUE TITLE
Processo de fix invalid geometry não identificou algumas autointerseções

### ISSUE THREAD

**Issue by rsmaior** [dsgoficial/DsgTools#384]
### Subject of the issue (Assunto do problema)
Quando rodo o processo de identificar e validar geometria, aconteceu de algumas autointerseções não serem identificadas e também não serem consertadas. Testei no QGIS 2.18 e nele sim foi identificado o problema. Coloquei em anexo os pacotes exemplificando.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional):  Kubuntu 16.04 e Windows 7 - 64 bits 
* version of QGIS (Versão do QGIS): 3.4.3 e 3.4.4
* version of DSGTools (Versão do DSGTools): 4.0 do branch de migração para o QGIS3 (commit 562e15b2f4e9835c96771433baf4a5de49140bc3)

### Steps to reproduce (Passos para reproduzir)
1) Carregar o arquivo em geopackage anexo no QGIS3. Escolher o processo de identificar e consertar geometria inválida. Verficar que ele não identifica nem corrige duas autointerseções.

2) Copiar e colar as feiçoes do geopackage para algum banco. Rodar o processo de identificar geometrias inválidas. Observar as duas ocorrências de autointerseção.

### Expected behaviour (Comportamento esperado)
Identificar e consertar as autointerseções.

### Actual behaviour (Comportamento atual)
As duas interseções não foram identificadas nem corrigidas.

Obs: seguem anexos o geopackage com as autointerseções e um shapefile com as flags que foram geradas no QGIS 2.

[shape_e_geopackage.zip](https://github.com/dsgoficial/DsgTools/files/2963113/shape_e_geopackage.zip)

**Comment by jpesperidiao** [comment]
A princípio, não consegui reproduzir o problema. É possível que alguma atualização do DSGTools ou do próprio QGIS já tenha sanado eventuais _bugs_.

**Comment by phborba** [comment]
@rsmaior vc pode testar por favor com a versão nova do QGIS (3.4.5)?

**Comment by rsmaior** [comment]
Testei aqui novamente com a última versão do branch migration (commit 233f4948b796426c3ce8594d4874f0fb7ded0da1). Kubuntu 16.04 e Windows 10. Continua não identificando. O @jpesperidiao testou com o QGIS 3.7 e Kubuntu 18.04, não conseguindo reproduzir o bug. Talvez tenham consertado algo para o QGIS 3.7
