### ISSUE TITLE
Processos identificar feições/geometrias duplicadas não funcionam

### ISSUE THREAD

**Issue by rsmaior** [dsgoficial/DsgTools#385]
### Subject of the issue (Assunto do problema)
Quando rodo o processo de identificar feições duplicadas no banco, nenhuma duplicata está sendo encontrada. Como exemplo, exportei a camada do trecho massa dagua do banco pra geopackage. Fiz um teste: criei duas camadas temporárias sem colunas ou atributos e fiz uma geometria em cima da outra. Rodei o processo e nela funcionou. Algumas vezes funcionou, outras não. Também exportei as duas camadas para geopackage.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional):  Kubuntu 16.04 
* version of QGIS (Versão do QGIS): 3.4.3
* version of DSGTools (Versão do DSGTools): 4.0 do branch de migração para o QGIS3 (commit 562e15b2f4e9835c96771433baf4a5de49140bc3)

### Steps to reproduce (Passos para reproduzir)
Carregar um dos arquivos anexos no QGIS3. Escolher o processo de identificar feições duplicadas. Verificar nas flags que ele só identificou uma das duplicatas da camada outro_teste.

### Expected behaviour (Comportamento esperado)
Identificar as feições duplicatas de todas as camadas.

### Actual behaviour (Comportamento atual)
Não identifica as feições duplicatas.

Obs: seguem anexos os geopackages com as camadas 
[camadas_feições_duplicadas.zip](https://github.com/dsgoficial/DsgTools/files/2967666/camadas_feicoes_duplicadas.zip)

**Comment by rsmaior** [comment]
Acontece algo similar com o identificar geometrias.

**Comment by phborba** [comment]
@rsmaior vc pode testar por favor?

**Comment by jpesperidiao** [comment]
Reabrindo o issue uma vez que o identificar __feições__ não está funcionando corretamente.
