### ISSUE TITLE
Converte Banco de Dados Spatialite para PostGis

### ISSUE THREAD

**Issue by jossanCosta** [dsgoficial/DsgTools#393]
### Subject of the issue (Assunto do problema)
Erro ao converter banco Spatialite para Postgis:
![conv_err](https://user-images.githubusercontent.com/20671795/58501584-25575c00-815b-11e9-8030-9a3e8201f1cc.PNG)

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional):  Windows 7
* version of QGIS (Versão do QGIS):  3.4
* version of DSGTools (Versão do DSGTools):  4.0

### Steps to reproduce (Passos para reproduzir)
Na ferramenta de converte banco selecionando um Spatialite de entrada e um PostGis de saída
colocando a opção "criar nova base de dados".

**Comment by phborba** [comment]
Não consegui reproduzir @jossanCosta , quais outras opções você colocou?

**Comment by jossanCosta** [comment]
Na entrada foi selecionado spatialite e na saída foi colocado PostGis , "criar nova base de dados" , EDGV 2.1.3 e Projeção 31982. Depois "terminal".
