### ISSUE TITLE
Bug na criação da moldura

### ISSUE THREAD

**Issue by LEOXINGU** [dsgoficial/DsgTools#396]
### Subject of the issue (Assunto do problema)
Não está sendo possível criar moldura no banco spatialite.
A seguinte mensagem aparece: 'module' object has no attribute 'osr'.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Windows 8
* version of QGIS (Versão do QGIS): 2.18
* version of DSGTools (Versão do DSGTools): mais recente 

### Steps to reproduce (Passos para reproduzir)
Procedimento normal até aparecer a mensagem da image:
![image](https://user-images.githubusercontent.com/25651083/59558549-36adbe80-8fcb-11e9-9c5b-7582994e9ae6.png)

**Comment by phborba** [comment]
Não daremos mais manutenção no DSGTools do QGIS 2 =/
