### ISSUE TITLE
Processo de identify and fix invalid geometries não funciona em batch process

### ISSUE THREAD

**Issue by diogooliveira-dsg** [dsgoficial/DsgTools#397]
### Subject of the issue (Assunto do problema)
ao tentar rodar a identificação de geometrias invalidas em batch o processo não é executado retornando erro

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional):  Windows 10
* version of QGIS (Versão do QGIS): 3.4.8
* version of DSGTools (Versão do DSGTools): qgis 3.0_migration (de 2019-06-19)

### Steps to reproduce (Passos para reproduzir)
1- camadas carregadas de banco postgis (carregado via DSGTools)
2- tentar roda o processo de identificar geometrias inválidas em batch
3- Imput Layer > select from opem layers > select all
4- flag em gpkg (tb apresenta erro em outros formatos)
5- autofill settings > Fill with parameter values > input layer

### Expected behaviour (Comportamento esperado)
retornar os gpkg das camadas com os flags

### Actual behaviour (Comportamento atual)
ocorre o seguinte erro python:
"2019-06-19T10:22:21     WARNING    Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins\processing\gui\BatchAlgorithmDialog.py", line 88, in runAlgorithm
              parameters[param.name()] = wrapper.parameterValue()
             AttributeError: 'NoneType' object has no attribute 'parameterValue'
"

**Comment by jpesperidiao** [comment]
@diogooliveira-dsg, como a mensagem de erro indicava ser um problema próprio QGIS, testei com algumas versões (todos no Kubuntu 18.04, na mesma máquina):

- QGIS 3.9.0: funcionando normalmente;
- QGIS 3.7.0: funcionando normalmente;
- QGIS 3.4.8: dá erro; e
- QGIS 3.4.10: funcionando normalmente.

Assim, acredito que a melhor solução seria adotar uma das outras versões. Cuidado com o problema apontado pelo @LEOXINGU, no issue #404. Este também aparenta ser um problema do QGIS e, após realizar os mesmo testes acima:

- QGIS 3.9.0: funcionando normalmente;
- QGIS 3.7.0: funcionando normalmente;
- QGIS 3.4.8: funcionando normalmente; e
- QGIS 3.4.10: apresenta o problema apontado no issue #404.
