### ISSUE TITLE
Problema na criação do BD Spatialite

### ISSUE THREAD

**Issue by LEOXINGU** [dsgoficial/DsgTools#398]
O DSG Tools está apresentando problema para a criação do BD spatialite, conforme figura abaixo:

![Capturar2](https://user-images.githubusercontent.com/25651083/59977140-04d8c100-95a4-11e9-8636-9cb789075eb8.JPG)

A mensagem do Log é a seguinte:
2019-06-23T10:16:26     CRITICAL    Erro em teste1: local variable 'edgvPath' referenced before assignment

Versão do DSG Tools (branch qgis3.0_migration)
Versão do QGIS: 3.4
SO: Windows 10

Att.

**Comment by jpesperidiao** [comment]
Consertado no commit [400767d](https://github.com/dsgoficial/DsgTools/commit/400767def83a4e6f913a91b37f48dd7eafe8fb73).

**Comment by LEOXINGU** [comment]
Funcionou aqui. Obrigado!
