### ISSUE TITLE
Bug para definir o SRC (projeção) na criação de BD

### ISSUE THREAD

**Issue by LEOXINGU** [dsgoficial/DsgTools#404]
Problema: 
A Ferramenta "Criar Banco de Dados" não permite definir o SRC (projeção) para as versões superiores ao 3.4.6, ou seja, não é possível selecionar o SRC, estando todas as opções desativadas, conforme figura abaixo:
![image](https://user-images.githubusercontent.com/25651083/61875147-6603f500-aec0-11e9-9e79-5a158eb3d91c.png)

No caso apresentado acima, está sendo utilizado o QGIS 3.4.10, no Windows 10 e DSGTools é a versão mais recente baixada no dia 24/07/19 deste Github (migration).

**Comment by jpesperidiao** [comment]
@LEOXINGU, não consigo reproduzir o problema. Testei com a versão em 3.7 (compilada ontem) no Kubuntu 18.04 e no Windows 10 (QGIS 3.4).

Foi executado algo antes, ou, por exemplo, se assim que iniciar o QGIS, sem sequer carregar camadas, o problema ocorre ao tentar criar o banco?

**Comment by jpesperidiao** [comment]
@LEOXINGU, testei com algumas versões do QGIS:

- QGIS 3.9.0: funcionando normalmente;
- QGIS 3.7.0: funcionando normalmente;
- QGIS 3.4.8: funcionando normalmente; e
- QGIS 3.4.10: apresenta o problema apontado no issue #404.

Sendo a 3.4.10 a versão mais recente do branch estável do QGIS, vou olhar se o issue foi resolvido/levantado e reportá-lo, caso não tenha sido.
