### ISSUE TITLE
bug no gerenciamento de permissões do DSGtools.

### ISSUE THREAD

**Issue by eduardojsilvajr** [dsgoficial/DsgTools#414]
### Subject of the issue (Assunto do problema)
ao dar a permissão para um usuário acessar um banco pelo DSGtools eu recebo o seguinte erro...
![image](https://user-images.githubusercontent.com/21279385/64290295-de37ee80-cf33-11e9-9e22-36eaca15a697.png)

### Your environment (Seu ambiente)
* your operating system (ubuntu 18.04.03): 
* version of QGIS (3.8.2): 
* version of DSGTools (4): 

### Steps to reproduce (Passos para reproduzir)
DSGtools -> ferramenta de servidor -> gerenciar banco de dados de servidor -> permissões -> gerenciar permissões de usuários.

### Expected behaviour (Comportamento esperado)
Deveria aparecer a mensagem de confirmação que a permissão foi dada/revogada do usuário

### Actual behaviour (Comportamento atual)
aparece a mensagem de erro em anexo ao confirmar volta-se pra tela anterior e ao confirmar novamente aparece a mensagem de confirmação que a permissão foi dada.

**Comment by phborba** [comment]
Corrigido no commit f40f0cc8ef6247ac45df655f22e2a3af32ef7dca
