### ISSUE TITLE
ET-EDGV_3.0 Dominios.Situacao_Fisica;

### ISSUE THREAD

**Issue by juliermegeotube** [dsgoficial/DsgTools#423]
Nota-se que o domínio situação_fisica possui dois valores repetidos:

SELECT * FROM dominios.situacao_fisica;
5 - Construída
7 - Construída

**Comment by phborba** [comment]
Boa tarde @juliermegeotube tudo bem? Verifique por gentileza se você criou o banco com o modelo novo. Pergunto pois a sql que foi lançada no DSGTools 4.0 está correta:

https://github.com/dsgoficial/DsgTools/blob/5785ca442a324543cbe1d9febe764c08916853a7/core/DbModels/PostGIS/3/edgv3.sql#L1556-L1570
