### ISSUE TITLE
Tabela db_metadata do spatialite da edgv 2.1.3 está faltando

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#429]
Está faltando a tabela db_metadata do modelo da edgv 213 corrigida na versão 4.0

**Comment by jpesperidiao** [comment]
Seguindo o padrão, adicionei a tabela "public_db_metadata" nas duas seeds de SpatiaLite que temos. A solução está no branch dev_#429.

Os dados populados, uma vez que não existiam anteriormente, os fiz mimetizando os das seeds de PostGIS.

@phborba, isso resolve?

**Comment by phborba** [comment]
Em tese sim, você preencheu a db_metadata com a versão da edgv e a versão de implementação que nem a sql de criação do postgis? Pergunto isso pois é necessário fazer. Tem 2 jeitos bem fáceis de preencher: um é usando o FME e outro é usando o QGIS (carregando a tabela e criando uma feição)

**Comment by phborba** [comment]
Resolvido!
