### ISSUE TITLE
Classe Elemento_Infraestrutura não apresenta em seu domínio do atributo "tipo" o valor "Subestação de energia"

### ISSUE THREAD

**Issue by rsmaior** [dsgoficial/DsgTools#433]
### Subject of the issue (Assunto do problema)
Na EDGV Pro 2.1.3, o é previsto que a classe **Elemento_Infraestrutura** possua **Subestação de energia** como um dos valores para o o domínio do seu atributo **tipo**. Porém, a camada Elemento_Infraestrutura não apresenta tal valor.

### Passos para reproduzir
1) Criar um banco EDGV 2.1.3 Pro
2) Carregar a camada Elemento_Infraestrutura 
3) Criar nova feição
4) No atributo "tipo", buscar o valor "Subestação de energia"

**Comment by dinizime** [comment]
Esse codelist deixou de ser utilizado pois Subestação de Energia é um complexo na EDGV 2.13. A aquisição correta é Grupo Transformadores (em Elemento de Infraestrutura) e Área de Energia (em Ocupação do Solo).

O complexo é construído durante a validação no Gothic.
