### ISSUE TITLE
 camadas EDGV Pro 2.1.3  sem o atributo tipoSecundario

### ISSUE THREAD

**Issue by rsmaior** [dsgoficial/DsgTools#434]
###  camadas EDGV Pro 2.1.3  sem o atributo tipoSecundario
Na EDGV Pro 2.1.3, o é previsto que as classes Elemento_Viario, Elemento_Infraestrutura,  Edificacao, Deposito, Ocupacao_Solo, Limite_Legal, Limite_Especial e Elemento_Transportes  possuam o atributo tipoSecundario Porém, as camadas carregadas pelo DSGTools não apresentam tal atributo.
Passos para reproduzir

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Kubuntu Linux 16.04 64 bits
* version of QGIS (Versão do QGIS): 3.4.5
* version of DSGTools (Versão do DSGTools): dev (commit https://github.com/dsgoficial/DsgTools/commit/023681435e33276a4e750eec8a48015ab97b6565)

### Steps to reproduce (Passos para reproduzir)
1) Criar um banco EDGV 2.1.3 Pro
2) Carregar uma das camadas listadas acima
3) Criar nova feição ou mesmo abrir a tabela de atributos
4) Observar que nenhuma possui o atributo tipoSecundario

### Expected behaviour (Comportamento esperado)
As camadas deveriam possuir o atributo tipoSecundario

### Actual behaviour (Comportamento atual)
As camadas não possuem o atributo tipoSecundario

**Comment by phborba** [comment]
Isso não é bug, é usado um conceito de filtro nas novas implementações que ainda não foi documentado.
