### ISSUE TITLE
bug na criação de banco de dados postgres

### ISSUE THREAD

**Issue by eduardojsilvajr** [dsgoficial/DsgTools#435]
### Subject of the issue (Assunto do problema)

ao tentar criar bancos de dados em postgis, ao clicar na aba para escolher o SRC a nova janela não permite a escolha do SRC

### Your environment (Seu ambiente)
* Ubuntu 18.04
* QGIS 3.4.13: 
* DSG tools 4.0(atualizado em 07 nov): 

### Steps to reproduce (Passos para reproduzir)
DSG tools -> Ferramentas BD -> Criar banco Postgis -> escolher SRC

### Expected behaviour (Comportamento esperado)
Uma nova janela tem que ser aberta permitindo a escolha do SRC

### Actual behaviour (Comportamento atual)
a janela abre, porém não permite nenhuma seleção.

![image](https://user-images.githubusercontent.com/21279385/68898026-0b0f3b80-0705-11ea-964b-15f51c91abc5.png)

**Comment by phborba** [comment]
Isso é bug do QGIS. Atualiza o QGIS q safa

**Comment by jpesperidiao** [comment]
O problema foi associado ao QGIS e a solução de atualizar parece ter resolvido o problema. Encerrando o _issue_, mas pode ser reaberto caso o problema reapareça.
