### ISSUE TITLE
EDGV_3.0.rod_trecho_rodoviario_l.nome

### ISSUE THREAD

**Issue by juliermegeotube** [dsgoficial/DsgTools#438]
Conforme à ET-EDGV@3.0 [conceitual](http://www.geoportal.eb.mil.br/portal/images/PDF/ANEXOS_ET_EDGV_3.0_210518.pdf), o atributo NOME está sendo herdado pelo trecho_rodoviario da classe de objeto Via_Deslocamnto, contudo o atributo NOME não consta no rol de atributos do modelo físico da ET-EDGV@3.0 instalado via DsgTools versão master. 

CIAO

**Comment by phborba** [comment]
Boa noite! Muito obrigado pelo feedback.

Segue o link do github com a sql que contém o atributo nome 

https://github.com/dsgoficial/DsgTools/blob/5785ca442a324543cbe1d9febe764c08916853a7/core/DbModels/PostGIS/3/edgv3.sql#L12797

Sugiro verificar sua instalação do DSGTools.
