### ISSUE TITLE
template_edgv_3

### ISSUE THREAD

**Issue by juliermegeotube** [dsgoficial/DsgTools#439]
@phborba , é possível notar que se existir no servidor postgres um banco template_edgv_3 de uma instalação anterior, ao instalar um novo banco via DsgTools, o template_edgv_3 não é atualizado. Como o banco template_edgv_3 não estava sendo atualizado, mesmo utilizando a versão 4.0 do DsgTools as classes de objetos estavam sendo criadas com base no template_edgv_3 que exisitia no banco. Assim, vejo que é necessário inserir no script de criação de banco edgv via DsgTools uma linha para atualizar ou drop algum template_edgv_3 existente no banco. Caso esse template na seja atualizado, os novos bancos são criados utilizando configurações deprecated.

**Comment by phborba** [comment]
Em tese se você criar o banco pelo DSGTools ele já faz isso. Você testou criando o banco pelo DSGTools?

**Comment by juliermegeotube** [comment]
Sim. O banco edgv3 foi criado pelo DsgTools, mas o template_edgv_3 não está
sendo atualizado durante a criação.

**Comment by jpesperidiao** [comment]
Realizei alguns testes e não consegui reproduzir o problema.

A princípio, já existe uma rotina de "_check, drop & create_" templates de acordo com a versão.

Os testes que eu fiz se resumem, basicamente, a introduzir uma versão mais recente no template em SQL em relação ao que está implementado no banco. Em nenhum dos casos testados o banco criado veio com a versão antiga.

Como apontado pelo @phborba, este é o comportamento esperado de criação desde que criado pelo próprio DSGTools.

@juliermegeotube, poderia conferir se o seu problema ainda existe? Se sim, poderia apontar os passos para a reprodução e informações de versões do DSGTools, QGIS e sistema operacional, por favor?

**Comment by jpesperidiao** [comment]
Irei encerrar o presente _issue_ uma vez que não consegui reproduzi-lo.

Caso o problema persista, podemos reabrir o problema com as informações necessárias para a reprodução.
