### ISSUE TITLE
Novas funcionalidades: Alternar visualização de camada e de vértices

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#443]
Depois de testes de Produção utilizando Ferramentas de Produção atual para o SAP 2 (https://github.com/1cgeo/Ferramentas_Producao/tree/master) as seguintes ferramentas foram consideradas úteis:

- Alternar visualização de camada: Ferramenta que liga e desliga a visualização da camada ativa. Antes era feito com dois atalhos utilizando atalhos padrão do QGIS.

- Alternar visualização de vértices: Ele alterna o modo de visualização de vértices de todas as feições para somente as feições selecionadas.

Acredito que ambas as ferramentas podem ser importadas para o DSGTools (e assim sairem do FP)

**Comment by phborba** [comment]
Diniz, a menos que eu tenha entendido errado, acho que essas funcionalidades já foram integradas ao DSGTools 4.0, conforme a figura abaixo
![image](https://user-images.githubusercontent.com/6131641/70460870-12243200-1a96-11ea-9ebf-aff9a15c5065.png)

São essas que você está falando?

**Comment by dinizime** [comment]
Não vi que já tinha adicionado. É isso aí emsmo.
