### ISSUE TITLE
Processo de validação de leis do modelado do terreno

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#460]
Processo de validação para verificar pontos cotados, curvas de níveis e drenagens. Verificações a serem feitas:

- [x] Curvas de cota diferente não devem se tocar;
- [x] Curvas de cota diferente não devem se intersectar;
- [x] Curvas devem ser fechadas ou tocarem (ou ultrapassarem) a moldura (sem pontas soltas dentro da moldura);
- [x] Curvas devem ser múltiplas da equidistância;
- [x] Verificação de curva faltando;
- [x] Verificação do empilhamento das curvas (proporção de área vs valor da cota);
- [x] Verificação das curvas de depressão;
- [x] Verificação de ponto cotado fora da equidistância;
- [x] Drenagens devem fluir de montante para jusante, sempre descendo;
- [x] Curva de nível deve cruzar TMD sem vértice dentro (regra do Gothic para forçar aquisição como previsto na ADGV);
- [x] Curva de nível de mesma cota não pode ter mais de uma intersecção com Trecho Massa D'água (processo semelhante ao de Drenagens devem fluir de montante para jusante, sempre descendo);

**Comment by dinizime** [comment]
Curva de nível não deve intersectar Massa Dágua

**Comment by dinizime** [comment]
Implementamos o protótipo do seguinte algoritmo: Drenagens devem fluir de montante para jusante, sempre descendo.
Uma vez testado com sucesso em produção iremos verificar a integração com DSGTools.

Verificamos que o caso de curva faltando não está detectando todos os casos, estamos testando alternativas.

Entrou na nossa lista de prioridade implementar os seguintes casos:

- Verificação de ponto cotado fora da equidistância
- Curva de nível deve cruzar TMD sem vértice dentro 
- Curva de nível de mesma cota não pode ter mais de uma intersecção com Trecho Massa D'água (processo semelhante ao de Drenagens devem fluir de montante para jusante, sempre descendo);
- Verificação do empilhamento das curvas, 

O caso restante: "Verificação das curvas de depressão" teriamos que especificar melhor exatamente o que vamos testar.

**Comment by dinizime** [comment]
Feito e testado:
- Consistencia entre fluxo e curva de nível (ferramentas experimentais)
- Verifica empilhamento de curva de nivel (dsgtools)

**Comment by phborba** [comment]
concluído no commit 27bd35c46a96114668bf48c66a8a9445c1a305ac .
