### ISSUE TITLE
Erro ao criar novo banco de dados

### ISSUE THREAD

**Issue by jessicaviannaco** [dsgoficial/DsgTools#462]
### Subject of the issue (Assunto do problema)
Erro ao criar novo banco de dados
### Your environment (Seu ambiente)
* Windows 7
* Versão Qgis 3.4
* version of DSGTools (Versão do DSGTools): 4.0

### Steps to reproduce (Passos para reproduzir)
Banco de Dados foi conectado com sucesso. Quando seleciono a opção Create a Postgis Database, ele dá erro.

![image](https://user-images.githubusercontent.com/34686494/71686893-46300180-2d7b-11ea-8d7b-6b573a3772cc.png)

### Expected behaviour (Comportamento esperado)
Criar banco de dados

### Actual behaviour (Comportamento atual)
Erro. Mensagem no log: CRITICAL Erro em dsg: 2:No such file or directory

**Comment by phborba** [comment]
Boa tarde @jessicaviannaco tudo bem? Muito obrigado pelo Feedback. Qual modelo de banco você tentou instalar?

**Comment by jpesperidiao** [comment]
Encerrando tendo em vista não haver mais problemas de criação de banco (verificar o PR #465) e inatividade do _issue_.

Caso haja problemas relacionados ao tópico, basta comentar neste _issue_, que será reaberto.
