### ISSUE TITLE
Topological Douglas Peucker Simplification not handling lines.

### ISSUE THREAD

**Issue by franciscocamellon** [dsgoficial/DsgTools#481]
### Subject of the issue (Assunto do problema)
In the Quality Assurance Tools, the simplify algorithm Topological Douglas Peucker Simplification don't handling lines.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Windows 10 Home Single Language
* QGIS version (Versão do QGIS): 3.10.4 LTR
* DSGTools version (Versão do DSGTools): dev

### Steps to reproduce (Passos para reproduzir)
1. open the algorithm
2. select multipe layers - there isn't an option to select the line layers.

![douglas_peucker_issue](https://user-images.githubusercontent.com/38926687/82323708-d7141c00-99ae-11ea-857d-de109bfcc5fc.png)

### Expected behaviour (Comportamento esperado)
Simplifying lines or multilines topologically.

### Actual behaviour (Comportamento atual)
Simplifying only polygons or multipolygons topologically.

**Comment by jpesperidiao** [comment]
Já está no 4.1 (RC) algoritmo para a simplificação de linhas.
