### ISSUE TITLE
complemento instala, mas não executa acusando que o Windows instalado "does not support the required Bluetooth API"

### ISSUE THREAD

**Issue by elizamaia** [dsgoficial/DsgTools#482]
### Subject of the issue (Assunto do problema)

Através do QGIS, após instalação da ferramenta, ele não executa dando a mensagem de que o Windows que tenho instalado "does not support the required Bluetooth API" e fecha o QGIS.

![erro_dsgtools](https://user-images.githubusercontent.com/53905848/82754093-107acc00-9da1-11ea-9e64-27ce4998582a.JPG)

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Windows 8.1
* version of QGIS (Versão do QGIS): 3.10.6
* version of DSGTools (Versão do DSGTools): 4.1 (versão disponibilizada no repositório do QGIS)

### Steps to reproduce (Passos para reproduzir)

1. Abrir o QGIS;
2. Abrir "Gerenciar e instalar complementos" na aba "Complementos";
3. Pesquisar a ferramenta DSG Tools e instalar;
4. Esperar a instalação terminar e o aviso aparecerá.

OBS.: a ferramenta fica como instalada no sistema. Para ver o erro de novo:

1. Abrir o QGIS;
2. Abrir "Gerenciar e instalar complementos" na aba "Complementos";
3. Ir em "Instalados";
4. Clicar 2 vezes no complemento "DSG Tools".

### Expected behaviour (Comportamento esperado)

O complemento deveria estar executável após sua instalação.

### Actual behaviour (Comportamento atual)

Dá o erro "This Windows version (6.3.9600) does not support the required Bluetooth API. Consider updating to a more recent Windows (10.0.10586 or above)." e fecha o QGIS.

**Comment by jpesperidiao** [comment]
Bom dia, @elizamaia, tudo bem?

Inicialmente, obrigado pelo _feedback_.

Sobre o _issue_ levantado, existe o #471, sobre o mesmo erro (só que em Windows 10). Nos comentários dele, tem um _link_ de apoio que indica que este erro é associado à Qt (_framework_ de interface que o QGIS usa, e usamos em consequência). Este erro, inclusive, estaria afetando outras aplicações.

A notícia ruim é que, sendo de uma biblioteca externa, não temos controle. Ainda estamos verificando formas de contornar. Daí, uma notícia "menos ruim": pelo que alguns fóruns sobre a Qt informam, este problema é associado a apenas algumas builds de Windows 8 e Windows 10, então atualizar o Windows e da Qt (no caso, por meio de atualização do QGIS), poderia resolver o problema.

**Comment by jpesperidiao** [comment]
Devido à inatividade e falta de perspectiva de solução por parte do projeto (pelo menos por enquanto), encerro o _issue_, embora possa ser reaberto, no caso de necessidade / atualizações.

**Comment by jpesperidiao** [comment]
@elizamaia, sei que não é a melhor das soluções, mas encontrei uma forma de "dar um jeito". Para que não haja o erro, pode-se suprimir as bibliotecas de relacionadas ao _bluetooth_ da Qt.

A princípio, a escopo do QGIS, não vejo problema, uma vez que qualquer uso deste módulo dá erro (inclusive um simples "from qgis.PyQt import Qt" da própria interface do QGIS gera o erro).

Para isso:

1- Acessar a pasta de bibliotecas de Python do QGIS: pelo instalador padrão da OSGeo, o caminho é `C:\OSGeo4W64\apps\Python37\lib\site-packages\PyQt5` (podendo haver alterações com relação a versão de Python, mas em linhas gerais, é este); e
2- renomei/remova os arquivos referentes a este módulo (`QtBluetooth.pyd` e `QtBluetooth.pyi`) - no meu caso, renomeei para `_QtBluetooth.pyd` e `_QtBluetooth.pyi`.

_Link_ de apoio: https://stackoverflow.com/questions/55205708/why-pyqt5-import-show-a-error-about-windows-and-bluetooth
