### ISSUE TITLE
Translate DSGTools for 4.1 release

### ISSUE THREAD

**Issue by jpesperidiao** [dsgoficial/DsgTools#486]
Initiate translation process for current *dev* branch.

Check DSGTools Project Guidelines for help.

**Comment by jpesperidiao** [comment]
@franciscocamellon já fez o grosso. Faltam ainda (esperando revisão/PR):

- [ ] tradução da Ferramenta de Classificação; e
- [ ] tradução dos componentes referentes ao suporte de GPKG.

**Comment by phborba** [comment]
Fiz o merge depois do @jpesperidiao ter autorizado.

**Comment by phborba** [comment]
@jpesperidiao o pull request estava para o master, vi só agora, acabou dando merge no master. Mas não tem problema, é só abrir um pull request do master pro dev pra deixar tudo ok. A boa notícia é que n deu conflito no master =]

**Comment by jpesperidiao** [comment]
Versão 4.1 (RC) disponível do branch de desenvolvimento principal, já traduzido.
