### ISSUE TITLE
Novo processo de validação: verificação de atributos

### ISSUE THREAD

**Issue by franciscocamellon** [dsgoficial/DsgTools#497]
#### Processo de validação de atributos.
Algoritmo no qual verifica-se a validade dos atributos apontando-se erros de consistência lógica e também a combinação de atributos incomuns ou inadequados.

Funcionalidades a serem abordadas:
- [x] importar regras de verificação
- [x] permitir elaboração de regras pela interface
- [x] verificação dos domínios
- [x] verificar se um atributo é nulo
- [x] verificar padrão de preenchimento do atributo(máscara)
- [x] verificar conjunto de atributos
- [x] exportar regras de verificação
- [x] criar camada com as flags de erro

**Comment by dinizime** [comment]
Essa ferramenta tem bastante sobreposição com o processing Rule Statistics. Imagino que o melhor caminho é criar uma interface que utilize por trás uma variação desse processing. Aí essa interface bate os critérios:
- importar regras de verificação
- permitir elaboração de regras pela interface
-  exportar regras de verificação

O Rule statistics já bate o critério **verificar conjunto de atributos**, porém teria que ser modificado para atender o critério **criar camada com as flags de erro**. Porém como eu disse ao @jpesperidiao é importante que ambos os comportamentos sejam atendidos, os flags de erro, porém o resumo dos erros (como está hoje no Rule Statistics) também. Pois na prática na produção o flag é bem inconveniente para esse caso, o resumo é o que utiliza na prática.
Então nessa interface sera interessante a opção para selecionar se ele quer exportar os flags ou só um resumo.

Sobre os outros requisitos: **verificação de domínio**, **verificação de atributo número**, e **verificar padrão de preenchimento do atributo(máscara)** são basicamente mais regras de atributação. Acredito que não precise de um comportamento distinto para esses casos.
