### ISSUE TITLE
Douglas Peucker Simplification delete features when onlySelected option is checked.

### ISSUE THREAD

**Issue by franciscocamellon** [dsgoficial/DsgTools#505]
### Subject of the issue (Assunto do problema)
Both Douglas Peucker Simplification algorithm, line and area, delete all nonselected features when onlySelected option is checked.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Windows 10 Home Single Language
* QGIS version (Versão do QGIS): 3.10.4 LTR
* DSGTools version (Versão do DSGTools): dev

### Steps to reproduce (Passos para reproduzir)
1. open the algorithm
1. select layers from available layer list
1. check the option Process only selected features

![douglasP](https://user-images.githubusercontent.com/38926687/94046599-49569c00-fda7-11ea-8b71-bdda8c7d1455.png)
4. Run the algorithm.
### Expected behaviour (Comportamento esperado)
Process only selected features keeping other features untouched.

### Actual behaviour (Comportamento atual)
The algorithm process only selected features deleting all other features.

**Comment by jpesperidiao** [comment]
Resolvido no PR #506. Teste de integração adicionado pelo @franciscocamellon.
