### ISSUE TITLE
Coluna consrc removida de pg_constraint para PostgreSQL 12+

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#521]
Para versões mais novas do PostgreSQL (12 e 13) a coluna consrc for removida do pg_constraint.

No changelog consta:

> Remove obsolete pg_constraint.consrc column (Peter Eisentraut)
> This` column has been deprecated for a long time, because it did not update in response to other catalog changes (such as column renamings). The recommended way to get a text version of a check constraint's expression from pg_constraint is pg_get_expr(conbin, conrelid). pg_get_constraintdef() is also a useful alternative.

Teria que verificar as alternativas propostas de forma a atender as versões 12 e 13 (mantendo suporte para versão 9, 10 e 11)

**Comment by jpesperidiao** [comment]
Coluna consrc foi removida das tabelas de metadados do PostgreSQL a partir da versão 12.

Existem métodos que utilizam esta coluna no código. Entretanto, estes métodos não estão sendo utilizados por quaisquer dos recursos ativos do DSGTools no momento.

São eles:

```python
PostgisDb.getInheritanceConstraintDict
PostGISSqlGenerator.getConstraints
PostGISSqlGenerator.getConstraintDict
```

Assim, foram apenas comentados no caso de existir algum uso não percebido, além de serem passíveis de uso na refatoração de código dos objetos de abstração de fontes de dados.
