### ISSUE TITLE
Requisito 1 - Validação da estrutura do banco de dados

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#522]
Implementar como processing o requisito 1 do Relatório Técnico nº 13/2020 - DGEO/1ºCGEO: 

> Verificar nomes de classes, nomes dos atributos, tipo e tamanho dos atributos, existência de todos os atributos, tipos geométricos válidos para cada classe, codificação de caracteres. Classes e atributos adicionais não são considerados erros.

**Comment by jpesperidiao** [comment]
Acho que é o caso deixar este _issue_ para o instante em que formos implementar a conversão entre modelagens EDGV distintas. Isto considerando o _refactor_ da parte de bancos de dados, em que pretende-se utilizar sempre o _masterfile_ como referência para operações com modelagens EDGV.

**Comment by dinizime** [comment]
Sim, não vou mexer nesse caso agora agora (por isso nem postei nada aqui dele) pois ele só será relevante quando diversos CGEO estiverem utilizando a validação no QGIS.
A ideia é que exista um controle de qualidade de um CGEO pelo outro da mesma forma que ocorre com o MGCP. E da mesma forma que ocorre com MGCP a início é verificar se a modelagem dos dados está conforme os metadados.
Lembrando que aqui vai ser aplicar versões de implementação da EDGV também, por exemplo já tiveram várias versões da EDGV 3.0 Pro, como só a gente está usando aqui eu consigo controlar isso, mas no momento que vários CGEO estiverem utilizando a modelagem esse controle de versão parcial tem que ser mais rígido.

Dentre os requisitos que eu levantei esse é a última prioridade.

**Comment by phborba** [comment]
Concluído pelo @matheusalsilva98 no PR #788
