### ISSUE TITLE
Requisito 12 - Polígono sliver

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#526]
Implementar como processing o requisito 12 do Relatório Técnico nº 13/2020 - DGEO/1ºCGEO:

> The primary participant is an area feature having a ratio of area to perimeter less than the primary tolerance.

**Comment by dinizime** [comment]
Entrou na nossa lista de prioridade de desenvolvimento.

**Comment by dinizime** [comment]
Model criado. Em teste na produção.

**Comment by dinizime** [comment]
Teoricamente não tem problema utilizar um model, funcionalmente o model é a mesma coisa que um processing. O plugin pode carregar o model automaticamente no provider, tem um exemplo disso aqui:
https://github.com/1cgeo/ferramentas_experimentais/blob/main/processings/provider.py

De qualquer forma está resolvido esse issue então, pode fechar quando der merge.

**Comment by jpesperidiao** [comment]
Revisado e com os testes funcionando. Ainda não consta na documentação da Wiki, mas estará em breve.
