### ISSUE TITLE
Requisitos 14 e 15 - Undershoot e overshoot de linha

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#527]
Implementar como processing o requisito 14 do Relatório Técnico nº 13/2020 - DGEO/1ºCGEO:

> The primary participant is a line feature end node that is not within the primary tolerance (2D distance) to any part of a secondary participant feature or to any part of a tertiary participant feature, but is within the secondary tolerance (2D distance) to some part (including any inter-node segment) of the secondary participant line feature and the two line features do not intersect on the primary participant segment defined by the point at which the undershoot is reported - this inspection can be configured to ignore undershoots involving nearly parallel and adjacent line features by setting appropriate 16 values in the 3rd and 4th tolerances - the 3rd tolerance sets a lower bound on undershoot magnitude for filtering to be applied (undershoots with magnitude < the 3rd tolerance will not be filtered) - the 4th tolerance sets a minimum length for adjacency of the undershoot features (features that have adjacent lengths less than the 4th tolerance will not be filtered)

> The primary participant is a line feature end node that is not within the primary tolerance (2D distance) to any part of a secondary participant feature or to any part of a tertiary participant feature, but is within the secondary tolerance (2D distance) to some part (including any inter-node segment) of the secondary participant line feature and these two line features are different feature types and they do not intersect on the primary participant segment defined by the point at which the undershoot is reported - this inspection can be configured to ignore undershoots involving nearly parallel and
adjacent line features by setting appropriate values in the 3rd and 4th tolerances - the 3rd tolerance sets a lower bound on undershoot magnitude for filtering to be applied (undershoots with magnitude < the 3rd tolerance will not be filtered) - the 4th tolerance sets a minimum length for adjacency of the undershoot features (features that have adjacent lengths less than the 4th tolerance will not be filtered)

Implementar como processing o requisito 15 do Relatório Técnico nº 13/2020 - DGEO/1ºCGEO:

> The primary participant is a line feature end node that is not within the primary tolerance (2D distance) to any part of a secondary participant feature or to any part of a tertiary participant feature, but is within the secondary tolerance (2D distance) to some part (including any inter-node segment) of the secondary participant line feature and the two line features intersect on the primary participant segment defined by the point at which the overshoot is reported - this inspection can be configured to ignore overshoots involving nearly parallel and adjacent line features by setting appropriate values in the
3rd and 4th tolerances - the 3rd tolerance sets a lower bound on overshoot magnitude for filtering to be applied (overshoot with magnitude < the 3rd tolerance will not be filtered) - the 4th tolerance sets a minimum length for adjacency of the overshoot features (features that have adjacent lengths less than the 4th tolerance will not be filtered)

> The primary participant is a line feature end node that is not within the primary tolerance (2D distance) to any part of a secondary participant feature or to any part of a tertiary participant feature, but is within the secondary tolerance (2D distance) to some part (including any inter-node segment) of the secondary participant line feature and these
two line features are different feature types and they intersect on the primary participant segment defined by the point at which the overshoot is reported - this inspection can be configured to ignore undershoots involving nearly parallel and adjacent line features by setting appropriate values in the 3rd and 4th tolerances - the 3rd tolerance sets a lower
17 bound on undershoot magnitude for filtering to be applied (undershoots with magnitude < the 3rd tolerance will not be filtered) - the 4th tolerance sets a minimum length for adjacency of the overshoot features (features that have adjacent lengths less than the 4th tolerance will not be filtered)

Já existe o processing "Identify Dangles" porém esse somente executa para uma classe e não necessairamente segue o pensamento descrito acima.

**Comment by dinizime** [comment]
Também atende o requisito 22 Undershoot e Overshoot de feições linha e área em relação a moldura.

**Comment by dinizime** [comment]
Requisito 22 Undershoot e Overshoot de feições linha e área em relação a moldura entrou na nossa lista de prioridade de desenvolvimento.

**Comment by dinizime** [comment]
Requisito 22 Undershoot sendo testado em produção.

Requisitos 14 e 15 entraram para nossa lista de prioridade.

**Comment by dinizime** [comment]
Feito um model para identificação de undershoot e overshoot entre camadas. Sendo testado em produção.

**Comment by phborba** [comment]
Processos portados para o DSGTools e novos implementados.
