### ISSUE TITLE
Requisito 17 - Linhas seccionadas sem motivo

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#528]
Implementar como processing o requisito 17 do Relatório Técnico nº 13/2020 - DGEO/1ºCGEO:

> Linhas/Áreas seccionadas sem mudança de atributo ou elemento de intersecção.

Não possui rotina de verificação porém possui o processo de correção

**Comment by dinizime** [comment]
Entrou na nossa lista de prioridade de desenvolvimento.

**Comment by dinizime** [comment]
Em teste de produção.

**Comment by phborba** [comment]
Implementado no DSGTools.
