### ISSUE TITLE
Requisito 20 - Distância entre feições menores que a tolerância

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#531]
Implementar como processing o requisito 20 do Relatório Técnico nº 13/2020 - DGEO/1ºCGEO:

> Distância entre feições menores que a tolerância

**Comment by dinizime** [comment]
Entrou para nossa lista de prioridades.

**Comment by dinizime** [comment]
Sendo testado em produção.

**Comment by phborba** [comment]
Resolvido pelo @pedro-mar no pull request #775 .
