### ISSUE TITLE
Requisito 28 - Relacionamento espaciais simples

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#532]
Implementar como processing o requisito 28 do Relatório Técnico nº 13/2020 - DGEO/1ºCGEO:

> Relacionamento espaciais simples – dentro de uma mesma classe ou entre classes, utilizando ou não filtros baseados em atributos, e testes espaciais conforme matriz DE-9IM

Enforce Spatial Rules já realiza essa validação porém não é capaz de aceitar o relacionamento espacial como DE-9IM.

**Comment by jpesperidiao** [comment]
Relacionado para a v4.2.

**Comment by jpesperidiao** [comment]
[PR](https://github.com/dsgoficial/DsgTools/pull/568) já foi aceito na [dev](https://github.com/dsgoficial/DsgTools/tree/dev), aguardando confirmação para encerrar o _issue_.

**Comment by dinizime** [comment]
Testei, está ok, pode encerrar o issue.
