### ISSUE TITLE
Requisito 34 - Verificação tamanhos mínimos

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#533]
Implementar como processing o requisito 34 do Relatório Técnico nº 13/2020 - DGEO/1ºCGEO:

> Verificação de tamanhos mínimos conforme a especificação para feições linha e área

Já existe os processos "Identify Small Lines", "Identify Small Polygons", porém é necessário facilitar o seu uso para verificar multiplas classes de forma fácil. (talvez um model?)

**Comment by dinizime** [comment]
Fizemos um protótipo que verifica multiplos tamanhos a partir de um CSV. Tambem considera que feições na moldura podem ter tamanho menor que o mínimo.

Feito um caso separado para feições pequenas em feições lineares que formam redes (drenagem, rodovia, etc). Nesse caso o tamanho mínimo só se aplica as pontas livres.

Estão sendo testados em produção.

**Comment by phborba** [comment]
Feito no pull request #777
