### ISSUE TITLE
Requisito 29 - Relacionamento espaciais complexos

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#535]
Documentar casos nesse issue para ver qual a melhor forma de implementar o requisito 29 do Relatório Técnico nº 13/2020 - DGEO/1ºCGEO:

> Relacionamento espaciais complexos.

Um exemplo é: "Uma passagem em nível ponto deve estar na interseção entre um Trecho Ferroviário e um Trecho Rodoviário"

Outros softwares de validação como o GAIT lidam com casos complexos criando uma rotina particular para cada caso (e agrupando casos onde possível)

**Comment by dinizime** [comment]
Para esses casos, pelo menos por enquanto, a ideia é fazer processings específicos de validação de um conjunto de classes relacionados. O processing só será aplicável para uma determinada modelagem dos dados.

A ideia original era fazer processings genéricos e montar a validação a partir deles, porém para agora de modo a ter uma versão inicial de uma validação completa para os projetos pilotos do QGIS seguiremos dessa forma.

Uma vez todos os casos listados e funcionais acredito que fique mais fácil de agrupar em processings genéricos.

**Comment by jpesperidiao** [comment]
Acho que podemos criar uma categoria para algoritmos específicos (p.ex. "EDGV 3.0"), de modo que fique claro para o usuário qual o caso de uso / situação resolvida pela rotina.

**Comment by dinizime** [comment]
Sim pode ser

**Comment by dinizime** [comment]
Será criado um grupo específico de processings para cada modelagem.
