### ISSUE TITLE
Construir polígonos por linha e centroide não está funcionando no QGIS 3.16

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#536]
### Subject of the issue (Assunto do problema)
Describe your issue here. (Descreva seu problema aqui).

O algoritmo de construir polígonos não está funcionando no QGIS 3.16, inclusive rodei os unittests localmente e eles estão quebrados também. Talvez possa ter ocorrido algum problema de quebra de compatibilidade na API. A mensagem de erro que aparece é:

Traceback (most recent call last):
File "/Users/philipeborba/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DsgTools/core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/removeDuplicatedGeometriesAlgorithm.py", line 111, in processAlgorithm
).format(inputLyr.name()))
RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted

Execution failed after 0.33 seconds

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): MacOS Catalina
* version of QGIS (Versão do QGIS): 3.16
* version of DSGTools (Versão do DSGTools): 4.1

### Steps to reproduce (Passos para reproduzir)
Tell us how to reproduce this issue. Please provide screenshots to further information. (Descreva os passos para reproduzir o problema. Por favor informe capturas de tela para informaçes adicionais)

Rodar o algoritmo de construir polígonos por linha e centroide.

### Expected behaviour (Comportamento esperado)
Tell us what should happen. (Nos informe o que deveria acontecer.)

Deveria aparecer polígonos construídos.

### Actual behaviour (Comportamento atual)
Tell us what happens instead. (Nos informe o que acontece ao executar o procedimento descrito.)

O processo não roda.

**Comment by dinizime** [comment]
Alguma atualização quanto a solução desse problema? @jpesperidiao

**Comment by jpesperidiao** [comment]
@dinizime pago hoje para o @LFP-Trabalho.

**Comment by dinizime** [comment]
Não consegui reproduzir esse erro exatamente, somente o erro que já informei ao @jpesperidiao, que são:
- a rotina não completa quando não se utiliza uma camada polígono como limite
- a rotina não está levando em consideração o "fields to ignore", resultando em flags com mais de um centroide distinto incorretos.

**Comment by dinizime** [comment]
O pull request Dev#561 foi mergeado no master, é isso mesmo?

**Comment by jpesperidiao** [comment]
Não, foi por acidente. Mas como vamos lançar a versão 4.2 em breve, não reverti (ainda). Só fiz o PR pro dev (e já dei merge lá).

**Comment by dinizime** [comment]
Tem alguma coisa que eu tenho que testar nesse branch? @jpesperidiao
