### ISSUE TITLE
Problemas ao carregar camadas SpatiaLite EDGV 3.0

### ISSUE THREAD

**Issue by afonsokp** [dsgoficial/DsgTools#537]
### Subject of the issue (Assunto do problema)
Problemas ao carregar camadas SpatiaLite EDGV 3.0

### Your environment (Seu ambiente)
Windows 10
QGIS 3.16.1
DSGTools 4.1

### Steps to reproduce (Passos para reproduzir)
Crio um banco de dados SpatiaLite utilizando o template da EDGV 3.0 (Menu DSGTools > Ferramentas de BD > Criar um banco de dados PostGIS ou SpatiaLite). Após, ao carregar qualquer camada (Menu DSGTools > Ferramentas de Camada > Carregar Camadas) deste SpatiaLite, só aparece o grupo no painel de camadas do QGIS. Não aparece a camada em si dentro do grupo, impossibilitando seu uso e edição.

No template EDGV 2.1.3, as camadas dentro do SpatiaLite são carregadas de forma correta. Já na versão 3.0 está acontecendo este bug.

**Comment by jpesperidiao** [comment]
Bom dia, @afonsokp, tudo bem?

Já conseguimos reproduzir o _issue_ apontado e estamos trabalhando para resolver o mais brevemente possível.

Assim que houver alguma atualização, avisaremos por aqui.

Desde já agradecemos o seu apoio e ficamos à disposição para novos problemas, dúvidas, sugestões etc.

**Comment by jpesperidiao** [comment]
@afonsokp, o problema foi resolvido e está disponível na versão [dev](https://github.com/dsgoficial/DsgTools/tree/dev).

Lembrando que nossas versões de desenvolvimento devem ser instaladas manualmente. Se precisar de ajuda, estamos à disposição.

Este ticket permanecerá aberto por um período aguardando a confirmação de conclusão.

**Comment by afonsokp** [comment]
@jpesperidiao testei a versão dev e está funcionando perfeitamente.
Obrigado!
