### ISSUE TITLE
Rotina "Executar FME Workspace Remotamente" não lista Workspaces do FME

### ISSUE THREAD

**Issue by rsmaior** [dsgoficial/DsgTools#539]
### Subject of the issue (Assunto do problema)
Rotina "Executar FME Workspace Remotamente" não carrega rotinas

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Kubuntu 18.04.05 64 bits
* version of QGIS (Versão do QGIS): 3.16.4
* version of DSGTools (Versão do DSGTools): 4.1 (master atual - commit https://github.com/dsgoficial/DsgTools/commit/bc9842b2717bce14d093c9689a0b5d1b97a9defa)

### Steps to reproduce (Passos para reproduzir)
Preencher o parâmetro Endereço do Servidor e clicar no ícone (re) carregar. Pode ser com valores variados tais como:
http://usuarioadministrador:senha@IP:porta
http://usuariocomum:senha@IP:porta
htttp://IP:porta
htttp://IP
IP

### Expected behaviour (Comportamento esperado)
Ter as Workspaces carregadas no campo Workspace

### Actual behaviour (Comportamento atual)
Não acontece nada.

### Other info (outras informações)
@jpesperidiao acredita que pode ter algo a ver com a forma que a rotina trata proxy

**Comment by jpesperidiao** [comment]
Já resolvido no PR do @elitonfilho e já teve o código portado para os padrões do DSGTools.
