### ISSUE TITLE
Ferramenta de (Re)Classificação: Número de resultados na aba quando se utiliza a filtragem

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#54]
Nesta ferramenta existe um filtro que facilita a busca por botões. Sugere-se quando a ferramenta estiver configurada para os botões serem organizados por abas, aparecer nelas a contagem de elementos encontrados pelo filtro.

**Comment by dinizime** [comment]
Um caso de uso melhor seria criar uma nova aba contendo o resultado da pesquisa. Assim não necessita desse requisito.

**Comment by jpesperidiao** [comment]
Resolvido na refatoração da Ferramenta de Classificação #496.

Está sendo criado uma nova aba com os botões filtrados, que contém a quantidade de botões encontrados.
