### ISSUE TITLE
Ferramenta de Workflow parou de funcionar no QGIS 3.16

### ISSUE THREAD

**Issue by rsmaior** [dsgoficial/DsgTools#540]
### Subject of the issue (Assunto do problema)
Ferramenta de Workflow não funciona no QGIS 3.16

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Kubuntu 18.04.05 64 bits
* version of QGIS (Versão do QGIS): 3.16.4
* version of DSGTools (Versão do DSGTools): 4.1 (master atual - commit https://github.com/dsgoficial/DsgTools/commit/bc9842b2717bce14d093c9689a0b5d1b97a9defa)

### Steps to reproduce (Passos para reproduzir)
Criar um workflow válido e rodar

### Expected behaviour (Comportamento esperado)
Completar a execução do workflow

### Actual behaviour (Comportamento atual)
Sempre retorna o estado de 'Falha'

### Other info (outras informações)
Foi testado em outras configurações com versões anteriores do QGIS e funcionou normalmente (Kubuntu/Windows com QGIS 3.4.x e QGIS 3.10.x)
@jpesperidiao testou também o Mac OS com QGIS 3.16 e não funcionou.

**Comment by jpesperidiao** [comment]
Resolvido no PR #542. Caso ainda haja algum problema, só acresecentar por aqui.

Disponível no branch *dev* @rsmaior.

**Comment by dinizime** [comment]
@jpesperidiao Poderia verificar ocm o @rsmaior se já pode fechar esse issue?

**Comment by rsmaior** [comment]
Tá funcionando no dev mais recente
