### ISSUE TITLE
Ferramenta de (Re)Classificação: aba genérica

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#55]
Atualmente a ferramenta de reclassificação trabalhar sem abas e com abas definidas pelas categorias da EDGV. Em alguns casos, seria interessante construir de maneira customizada os grupos com os quais os botões seriam agrupados.

**Comment by jpesperidiao** [comment]
Resolvido na refatoração da Ferramenta de Classificação #496.
