### ISSUE TITLE
Topological Clean apagando todas as feições

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#551]
Ao executar topological clean em qualquer camada de linha (mesmo uma de memória com uma única linha), resulta no processing apagar todas as feições da camada.

Teste em Windows 10, QGIS 3.18.2 e 3.16.6. Camadas em sistema métrico (31974)

**Comment by jpesperidiao** [comment]
Vou começar a mexer nesse _issue_ hoje.
