### ISSUE TITLE
Adicionar opção de área na rotina donut hole extractor

### ISSUE THREAD

**Issue by rsmaior** [dsgoficial/DsgTools#552]
### Subject of the issue (Assunto do problema)
Adicionar a opção de área do anel que será exluída, de forma que áreas maiores serão mantidas.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Kubuntu 18.04.05 64 bits
* version of QGIS (Versão do QGIS): 3.16.5
* version of DSGTools (Versão do DSGTools): 4.1 (master atual - commit https://github.com/dsgoficial/DsgTools/commit/bc9842b2717bce14d093c9689a0b5d1b97a9defa)

### Steps to reproduce (Passos para reproduzir)
Abrir a rotina e converir que não existe o parâmetro.

### Expected behaviour (Comportamento esperado)
A rotina exclui qualquer anel de área menor que a definida pelo usuário.

### Actual behaviour (Comportamento atual)
A rotina extrai qualquer anel.

**Comment by dinizime** [comment]
Protótipo implementado, sendo testado em produção.
