### ISSUE TITLE
Importar e exportar regras no snap hierárquico

### ISSUE THREAD

**Issue by renanpena** [dsgoficial/DsgTools#557]
Importar e exportar regras no snap hierárquico
Seria interessante ter a possibilidade de importar e exportar regras na ferramenta de snap hierárquico

Seu sistema operacional: Windows 7 
* version of QGIS (Versão do QGIS):  QGIS 3.16
* version of DSGTools (Versão do DSGTools): 4.2 dev 

Seria interessante ter a possibilidade de importar e exportar regras na ferramenta de snap hierárquico

![snap hierarquico](https://user-images.githubusercontent.com/61280762/119843655-205e4c00-bede-11eb-8796-167bc4b2e2db.PNG)

**Comment by dinizime** [comment]
@sgtrenan uma solução parcial até desenvolver essa opção é fazer um modelo só com o Snap Hierarquico dentro, e configurar da forma que deseja e salvar o modelo.
Quando for executar o modelo ele não vai ter parâmetros e já vai executar conforme sua configuração.

**Comment by renanpena** [comment]
@dinizime Vou utilizar essa solução. Muito obrigado.

**Comment by phborba** [comment]
Feito pelo @pedro-mar no pull request #775
