### ISSUE TITLE
Avaliar impacto chave primária UUID e sistema 4674

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#560]
No próximo teste de produção vamos utilizar um banco com chave primária UUID e trabalhar diretamente em 4674. Tal teste é para a produção ser no mesmo padrão do MGCP.

Temos que avaliar as diversas ferramentas e processings o impacto dessas modificações.

**Comment by dinizime** [comment]
- [ ] Ferramenta de angulo reto não funciona corretamente me 4674. Imagino que a configuração de tamanho mínimo do lado está sendo considerado em graus.

**Comment by jpesperidiao** [comment]
> Imagino que a configuração de tamanho mínimo do lado está sendo considerado em graus.

Acho que o @ronaldomsjr chegou a resolver isso (ou pelo menos parte disso) no #338.

**Comment by dinizime** [comment]
Não resolveu então, testei no Dev e o problema permanece.

**Comment by dinizime** [comment]
A ferramenta Gabarito de Feições também não funciona corretamente em lat/long.

**Comment by jpesperidiao** [comment]
Editei na lista de observações original para dar uma centralizada!

**Comment by jpesperidiao** [comment]
@dinizime, resolvi os 2 problemas no [dev_#560](https://github.com/dsgoficial/DsgTools/tree/dev_%23560). Já está em condições de fazer o PR, mas não sei se é o caso encerrar este _issue_, dado que está centralizando as ocorrências com os testes com CRS em coordenadas geográficas.

Resolvi um terceiro problema, que não sei se ocorre por aí, mas o QGIS dá erro e encerra abruptamente quando ativa a ferramenta de aquisição de feições com ângulos retos (percebi apenas nas 3.16+).

**Comment by dinizime** [comment]
Vou verificar. Mas vamos deixar o issue aberto pois já estamos fazendo um projeto aqui testando a produção com chave primária UUID e sistema 4674, então mais situações podem ocorrer.

**Comment by dinizime** [comment]
A ferrmaent

> @dinizime, resolvi os 2 problemas no [dev_#560](https://github.com/dsgoficial/DsgTools/tree/dev_%23560). Já está em condições de fazer o PR, mas não sei se é o caso encerrar este _issue_, dado que está centralizando as ocorrências com os testes com CRS em coordenadas geográficas.
> 
> Resolvi um terceiro problema, que não sei se ocorre por aí, mas o QGIS dá erro e encerra abruptamente quando ativa a ferramenta de aquisição de feições com ângulos retos (percebi apenas nas 3.16+).

A ferramenta de ângulo reto está ok, funcionou sem problemas.

A ferramenta de área mínima continua não funcionando, agora está aparecendo uma mensagem.

**Comment by jpesperidiao** [comment]
Tinha esquecido de testar o formato circle com área como parâmetro. Acho que agora está OK.

Sobre a mensagem, eu coloquei porque a solução para adequar ao canvas em CRS não métrico é uma aproximação e, por isso, achei que seria o caso alertar o usuário (mas a ferramenta funciona normalmente).

**Comment by phborba** [comment]
@jpesperidiao pelo o que eu entendi, o que o @dinizime quer é que a ferramenta funcione também com sistemas não métricos, como 4674. No MGCP, por exemplo, há vários países que produzem em sistema não métrico, daí a motivação de fazermos um projeto piloto para avaliar os impactos de produzir dessa forma. Sendo assim, acho que é o caso ajustar a ferramenta para funcionar em coordenadas não métricas, ao invés de só dar um aviso e ela continuar não funcionando.

**Comment by jpesperidiao** [comment]
@phborba, ela tá funcionando. Vê esse GIF:

![area_minima](https://user-images.githubusercontent.com/19390778/125092064-52e79100-e0a7-11eb-8cf6-b6ab092f96e9.gif)

Só que do jeito que ela foi concebida, está otimizada para CRS métrico (a diferença não diria que é significativa, mas existe). Anteriormente, inclusive, tinha uma mensagem avisando que não funcionava com CRS não métrico. Aí, por isso, deixei a mensagem de alerta, somente.

**Comment by phborba** [comment]
Uma dúvida: a ferramenta atualiza o rubberbend quando vc troca o crs do canvas enquanto usa? Pergunto pois não lembro (tenho q olhar o código), mas tenho a impressão de que quando está desenhando, usa o que ele já pegou anteriormente. Nessa situação, talvez o teste que você mostrou possa não ser o mais apropriado. Eu ainda não testei e estou falando de intrometido mesmo, mas seria bom dar uma olhada nisso. O que acha @dinizime ?

**Comment by jpesperidiao** [comment]
Troca sim, toda vez que redesenha (no event moveCanvas, por exemplo) a rubberband ela checa pelo CRS carregado

**Comment by phborba** [comment]
Ahh entendi, eu realmente não lembrava disso mesmo, tem quase 3 anos que não mexo nela, memória de peixinho dourado aqui.

Essa camada de polígono que você construiu, ela é em sistema métrico ou geográfico? Eu pergunto para ver se as coordenadas que foram criadas se estão em graus ou metros mesmo.

**Comment by phborba** [comment]
Outra coisa, qual versão do QGIS vc está testando @jpesperidiao ? E você @dinizime ? Talvez possam estar olhando em versões diferentes e talvez possa ser o motivo de estar funcionando em um e não estar em outro.

**Comment by dinizime** [comment]
3.18.3 e 3.16.8, sistema 4674, o gabarito de circulo está com o tamanho gigante.
O gabarito de quadrado acredito que esteja ok.

Essa mensagem é bem incoveniente, acredito que atrapalhe o operador.

Também quando usa a ferramenta utilizando um atalho (a gente utiliza sempre atalho aqui) o gabarito não aparece imediatamente, necessitando mover o mouse.

**Comment by jpesperidiao** [comment]
O círculo não tava funcionando pq tinha esquecido aplicado a conversão num instante errado, no _commit_ anterior. Já tinha corrigido quando gravei o .gif.

Tirei a mensagem de alerta sobre o CRS.

**Comment by dinizime** [comment]
> O círculo não tava funcionando pq tinha esquecido aplicado a conversão num instante errado, no _commit_ anterior. Já tinha corrigido quando gravei o .gif.
> 
> Tirei a mensagem de alerta sobre o CRS.

Beleza, só olhar essa questão que o gabarito não aparece imediatamente necessitando mover o mouse, aí fecha essa ferramenta

**Comment by jpesperidiao** [comment]
Deu um pouco mais de trabalho que o esperado, mas tá feito o desenho mediante chamada de atalho.

**Comment by dinizime** [comment]
> Deu um pouco mais de trabalho que o esperado, mas tá feito o desenho mediante chamada de atalho.

Testado, tudo ok!
