### ISSUE TITLE
Restrição espacial não é aplicado no algoritmo de Construção de polígonos a partir de centroides

### ISSUE THREAD

**Issue by LFP-Trabalho** [dsgoficial/DsgTools#561]
### Subject of the issue (Assunto do problema)

O geographicBoundary não limita geograficamente o problema, apenas adicionas a linhas no linesconstrains. Ainda, o attributeblacklist não é levado adiante durante a processamento, sendo ignorado 

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Ubuntu 18.04
* version of QGIS (Versão do QGIS): 3.16.7
* version of DSGTools (Versão do DSGTools): 4.2_dev

**Comment by phborba** [comment]
A moldura é usada no algoritmo de construção de polígonos como mais uma linha auxiliar. O que vocês pensam por aplicar restrição espacial? Não entendi o issue.

**Comment by jpesperidiao** [comment]
@phborba, sim. Porém o que foi levantado, e eu concordei, é quando se passa uma camada de `limites geográfico`, entende-se que este, além de servir como delimitador, teriam a atribuição de restringir a área que se deve considerar construir os polígonos.

Por exemplo:

![image](https://user-images.githubusercontent.com/19390778/123442891-bce23f80-d5ab-11eb-95b5-e5ec55cbac62.png)

Se o polígono em vermelho é passado como limite, o algoritmo deveria criar apenas 1, 2 e 3.

Se o polígono é passado como delimitador tipo polígono, os polígonos criados seria 1, 2, 3, 4 e 5.

**Comment by dinizime** [comment]
Esse problema é simples de resolver. No FME eu faço da seguinte forma:
1) Filtro os centroides pela moldura
2) Filtro os poligonos resultante pela moldura com o relacionamento T********
