### ISSUE TITLE
Reshape freehand

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#562]
### Subject of the issue (Assunto do problema)
Bug na ferramenta de reshape de freehand.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Windows 10
* version of QGIS (Versão do QGIS):  3.18.2
* version of DSGTools (Versão do DSGTools): Dev

### Steps to reproduce (Passos para reproduzir)
Tentar da reshape com o freehand numa feição polígono ocorre o seguinte erro:

`Traceback (most recent call last):
  File "C:/Users/Diniz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DsgTools\gui\ProductionTools\MapTools\FreeHandTool\models\acquisitionFree.py", line 249, in canvasReleaseEvent
    self.finishEdition(event)
  File "C:/Users/Diniz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DsgTools\gui\ProductionTools\MapTools\FreeHandTool\models\acquisitionFree.py", line 340, in finishEdition
    self.doReshape(geom)
  File "C:/Users/Diniz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DsgTools\gui\ProductionTools\MapTools\FreeHandTool\models\acquisitionFree.py", line 348, in doReshape
    line = geom.asPolygon()[0]
TypeError: MultiPolygon geometry cannot be converted to a polygon. Only single polygon or curve polygon types are permitted.`

**Comment by dinizime** [comment]
Freehand vai ser nativo no 3.20.
https://changelog.qgis.org/en/qgis/version/3.20/#add-streaming-digitizing-mode

Então essa ferramenta mais no futuro será descontinuada, porém até lá é bom que esteja funcionando corretamente.

**Comment by jpesperidiao** [comment]
Sim, talvez fosse o caso de, na próxima LTR, lançarmos o DSGTools v5. E, neste, remover os casos que há sobreposição de ferramentas (o histograma dinâmico, por exemplo, acho que está nativo).

Os casos que há pequenas modificações, poderíamos estudar uma forma de substituir agregando o diferencial na ferramental nativa. Por exemplo:

No caso da Freehand, vejo a possibilidade de conectarmos o sinal maptool trocada, de modo que se checasse se o usuário gostaria de aplicar a suavização (poderia ser um botão toggle que indicaria se o usuário quer ou não a funcionalidade ativa).

Assim manteríamos a nossa particularidade (o que incluiria a possibilidade de atalho) e usaríamos a ferramenta deles. Neste cenário, poderíamos ativá-la para outras maptools, como a própria ferramenta de aquisição "normal".

**Comment by phborba** [comment]
DSGTools v5? Vai ter mudança brusca @jpesperidiao ? Depois dá uma olhada em semantic versioning, para ver se é o caso de trocar a major version mesmo.

Se tiver, é isso mesmo! =]

**Comment by jpesperidiao** [comment]
Não por agora, @phborba. Digo que sairia a v5 quando a gente fosse retirar essas ferramentas que estão "sobrepostas" pelas do QGIS, o que seria uma grande mudança. Isso seria na próxima LTR (3.22, salvo engano), porém.

**Comment by jpesperidiao** [comment]
@dinizime, PR submetido para verificação.

**Comment by dinizime** [comment]
Está funcionando OK
