### ISSUE TITLE
DSG Tools apresentando Provedor não válido

### ISSUE THREAD

**Issue by patrickazevedo** [dsgoficial/DsgTools#567]
### Subject of the issue (Assunto do problema)
O meu Qgis tá dando provedor inválido em todas as camadas de mapas existente no DSG tools
Está dando a seguinte mensagem

**Camada Inválida: Raster layer Provedor não é válido (provedor: wms, URI: crs=EPSG:4326&dpiMode=7&featureCount=10&format=image/png&layers=ctm100&styles&url=http://bdgex.eb.mil.br/mapcache**

Porém, quando eu uso o link direto wms que tenho, dá certo.
Já desinstalei o Qgis, limpei o registro, instalei tudo de novo e nada. Todos os outros serviços de mapas estão funcionando. Apenas esse não está indo.

Também verifiquei OPÇÕES, PROCESSAMENTO, PROVEDORES E O DSG TÁ ATIVO LÁ TAMBÉM.

O que pode ser?

Desde já agradeço

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional):  Windows 10 Pro
* version of QGIS (Versão do QGIS): 3.16.8-Hannover
* version of DSGTools (Versão do DSGTools): 4.1

### Steps to reproduce (Passos para reproduzir)
Com Qgis aberto fui em na ferramenta DSGTTools, em seguida vou em BDGEx, Cartas Topográficas, e selecionao 1:100.000 (ou qualquer outra)

### Expected behaviour (Comportamento esperado)
Deveria carregar um serviço de mapas do Brasil como imagem de fundo (wms)

### Actual behaviour (Comportamento atual)
Ao invés de aparecer a imagem de fundo, da um erro com a seguinte mensagem:
**Camada Inválida: Raster layer Provedor não é válido (provedor: wms, URI: crs=EPSG:4326&dpiMode=7&featureCount=10&format=image/png&layers=ctm100&styles&url=http://bdgex.eb.mil.br/mapcache**

**Comment by jpesperidiao** [comment]
Boa tarde, @patrickazevedo. Corrigimos um _issue_ há pouco tempo envolvendo camadas do BDGEx #563. O problema, neste caso, era com uma atualização do serviço e já o corrigimos.

Você poderia testar com a versão de desenvolvimento (branch [dev](https://github.com/dsgoficial/DsgTools/tree/dev)), por favor?

Para a instalação de versões em desenvolvimento, siga os passos:

1. baixar o _plugin_ na sua versão de desenvolvimento (link: https://github.com/dsgoficial/DsgTools/archive/refs/heads/dev.zip);
2. descompactar o arquivo e trocar o nome da pasta `DsgTools-dev` -> `DsgTools`;
3. copiar a pasta para o diretório de plugins do QGIS;
> Um atalho para abrir a pasta de maneira mais fácil siga os passos:
> a. acesse o menu `Configurações` / `Settings`;
> b. acesse no menu `Perfis de usuário` / `User profiles`;
> c. clique no menu `Abrir pasta do perfil ativo` / `Open active profile folder`;
> d. ao abrir a pasta, acesse a pasta `python`;
> e. acesse a pasta `plugins` (se não existir, criar com o nome todo minúsculo e no plural);
> f. se o DSGTools já estiver instalado, a pasta já existirá, então remova-a;
> g. cole a pasta descompactada e renomeada no diretório aberto; e
> h. reinicie o QGIS.
4. é possível que o _plugin_ fique desabilitado ao reiniciar, então basta ativá-lo na parte de complementos.

**Comment by patrickazevedo** [comment]
Perfeito... Vou realizar os procedimentos e retorno com o feedback

Por ora, muito obrigado

Patrick Azevedo
Mapeamento
Geoprocessamento
Graduando Análise e Desenvolvimento de Sistemas.

Em qui., 24 de jun. de 2021 15:51, João P. Esperidião <
***@***.***> escreveu:

**Comment by patrickazevedo** [comment]
Ola meu amigo.

A mensagem de erro não está mais aparecendo. Mas, todos os Raster que abre
(1:100.000, 50:000, 250.000, etc) aparece em branco, sem imagem de fundo.
Qas aparece algum trecho quando vai usando as bolinha do mouse para dar
zoom e acontece o mesmo no compositor de mapas, as vezes aparece e as vezes.

Seria alguma configuração do Qgis ou do Computador?

atenciosamente

Patrick Azevedo

Em qui., 24 de jun. de 2021 às 17:03, Patrick Azevedo <
***@***.***> escreveu:

**Comment by jpesperidiao** [comment]
Bom dia, @patrickazevedo. Testamos aqui e não conseguimos reproduzir ainda esse problema. Ainda faltam alguns outros testes, porém.

Isso ocorre em outras máquinas? É possível que seja alguma configuração de rede / proxy, ou algo do tipo.

Notei que há vezes em que uma das camadas de fato não carrega sem mexer no nível de _zoom_ do canvas. Já passei isso para o pessoal do BDGEx.

**Comment by patrickazevedo** [comment]
Ola meus amigos 

Mesmo com a versão Dev não funcionou. 
Hoje pela manha apresentou uma mesagem diferente.

**camadas do bdgex (dsgtools) : não foi possível carregar a camada solicitada. por favor, verifique suas configurações de rede (proxy e suas exceções também, se for o seu caso)**

Desinstalei Antivirus achando que havia feito algum bloqueio mas não deu em nada.

O problema é que não sei nem onde posso ir na rede para ver onde é a raiz do probelma. Você podem me orientar.

Outros computadores aqui estão acessando normalmente. Gostaria de ver se consigo resolver sem ter que formatar o PC somente conta disso.

**Comment by patrickazevedo** [comment]
Boa noite João
Descobri que o problema estava no roteador wireless que foi trocado e veio
configurado de maneira personalizada. Eu restaurei o roteador para
configurações de fábrica e apenas acrescentei um nome e senha para o acesso
wifi, mantendo as demais configurações nativas do roteador. Desse modo,
tudo voltou a funcionar normalmente.
Pra ser mais exato, era as configurações de ip, máscara de rede e gateway
que estavam com dados não muito comuns. Não sei se isso faz muito sentido
mas seja lá o que era, depois do reset, tudo voltou ao normal.
Resolvi deixar esse relato para que não fiquem dúvidas posteriores sem
solução.

Agradeço a você pelo suporte.

Obrigado.

Atenciosamente
Patrick Azevedo

Em sex., 25 de jun. de 2021 às 10:05, João P. Esperidião <
***@***.***> escreveu:

**Comment by jpesperidiao** [comment]
Bom dia, @patrickazevedo, de fato é importante o _feedback_.

Complementamos os testes e não conseguimos reproduzir, então não posso afirmar com certeza, mas ao que tudo indica de fato foi algo com a configuração de rede mesmo.

Como o seu problema, em princípio, foi resolvido, irei encerrar o _issue_. Caso queira continuar a discussão, basta comentar por aqui mesmo.
