### ISSUE TITLE
 Generate Systematic Grid gera MIs que não existem

### ISSUE THREAD

**Issue by elitonfilho** [dsgoficial/DsgTools#569]
### Subject of the issue (Assunto do problema)
A ferramenta utmGrid retorna MIs que não existem

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Windows 10 Build 19042.1052
* version of QGIS (Versão do QGIS): 3.18.1
* version of DSGTools (Versão do DSGTools): 4.2_dev_5929378c03c154bf1f9c744fe3a45cc3ff402100

### Steps to reproduce (Passos para reproduzir)
No processing Generate Systematic Grid, inserir no campo Index um MI que não existe (fora do país), como 1-3 (001-3)

### Expected behaviour (Comportamento esperado)
A rotina deveria lançar um erro, informando que o MI não existe

### Actual behaviour (Comportamento atual)
Ocorre a geração do polígono do MI.

**Comment by dinizime** [comment]
Resolvido em bc69e9f13713d9db575d165108c51b4b94238926
