### ISSUE TITLE
Novo requisito Verify Drainage Network Directioning

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DsgTools#573]
Conforme Relatório Técnico nº 07/2021 - DGEO/1ºCGEO - Dificuldades encontradas na produção de geoinformação básica para o Exercício Uraricoera é necessário separar as rotinas de direcionamento da rede de drenagem e de verificação do direcionamento da rede de drenagem.

Além disso é necessário modificar da lógica da rotina de direcionamento da rede de drenagem de modo a não utilizar o ângulo entre feições para inferir o direcionamento.

Apontamentos de ângulos conflitantes com o direcionamento pode ser um novo processing separado.

**Comment by dinizime** [comment]
Sendo desenvolvido no Ferramentas Experimentais para teste em produção.

**Comment by phborba** [comment]
Feito no pull request #768
