### ISSUE TITLE
Ferramenta de (Re)classificação: Checkbox para filtrar dinamicamente os botões exibidos pela camada ativa do QGIS

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#61]
Permitir a possibilidade de filtrar alguns botões pela camada ativa do QGIS.

**Comment by jpesperidiao** [comment]
A princípio, este comportamento poderia confundir o usuário e a opção de busca resolve este requisito (colocando-se o nome da camada como argumento de busca).
