### ISSUE TITLE
Gabarito de Feições: Rotação do gabarito

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#64]
Para permitir um melhor entendimento por parte do usuário, sugere-se habilitar a rotação do gabarito de feições. Tem-se um comportamento desejado que é ao segurar o Control, o movimento do mouse causaria a rotação do gabarito, rotação esta que seria terminada ao soltar o Control.

**Comment by jpesperidiao** [comment]
Fechado no commit [27ee7b9](https://github.com/dsgoficial/DsgTools/commit/27ee7b9d59af89ac7b8dfb1fb384275b127567af).

**Comment by phborba** [comment]
Achei bug, reportei no issue #182.
