### ISSUE TITLE
No maptool Set Value From Point não aparece o campo cota

### ISSUE THREAD

**Issue by franciscocamellon** [dsgoficial/DsgTools#663]
### No maptool Set Value From Point não aparece o campo cota
o maptool não disponibiliza o campo cota para escolha de onde guardar o valor retirado do MDT e/ou MDS

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Windows
* version of QGIS (Versão do QGIS): 3.22.4
* version of DSGTools (Versão do DSGTools): 4.3.1

### Steps to reproduce (Passos para reproduzir)
Menu DSGTools
    -> Ferramentas de Produção
        -> DSGTools: Set Value from Point

### Expected behaviour (Comportamento esperado)
Mostrar para escolha o atributo cota

### Actual behaviour (Comportamento atual)
Mostra somente os atributos do tipo numérico. Na modelagem o campo cota é do tipo string confome a figura abaixo
![image](https://user-images.githubusercontent.com/38926687/172438298-456822b9-6618-41cd-b592-cecad8ab3d0d.png)  

#### A seguinte correção foi testada e obteve sucesso:  
![image](https://user-images.githubusercontent.com/38926687/172438683-a1559938-14a4-4c29-8ead-9a4042689496.png)

### Improvement suggestion (Sugestão de melhoria)  
Desativar a ferramenta pelo click do botão direito do mouse, adicionando essas linhas de código  
![image](https://user-images.githubusercontent.com/38926687/172442742-85f24947-eabf-464c-9935-481d2634a815.png)  

e descomentando essa linha  
![image](https://user-images.githubusercontent.com/38926687/172443101-ddd84e1e-2f8b-48a9-8025-50f82b781a9c.png)

**Comment by dinizime** [comment]
Acredito que o erro seja na modelagem em si que vocês estão usando, cota não deveria ser varchar.

No git modelagens nenhuma das modelagens utilizam varchar para a cota.

Desta forma sugiro não realizar tal modificação no DSGTools e corrigir o banco de dados.
