### ISSUE TITLE
Ferramenta de seleção genérica: Seleção de feições de classes distintas de mesma primitiva

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#68]
Atualmente, quando a tecla Control está pressionada, a ferramenta de seleção genérica seleciona feições independentemente da classe e da primitiva. Deseja-se modificar o comportamento desse caso de uso para ao invés de seleção de feições independentemente da primitiva, para seleção de feições com primitiva igual a primitiva da primeira feição selecionada.

**Comment by jpesperidiao** [comment]
Feito no commit [e8a9003](https://github.com/dsgoficial/DsgTools/commit/e8a90034687bb27b8b54843a8c356218b9c4e500) do branch [3.2_dev_GenericSelection_#68](https://github.com/dsgoficial/DsgTools/tree/3.2_dev_GenericSelection_%2368).

**Comment by jpesperidiao** [comment]
Bugs encontrados. Voltei pro `In Progress`.

**Comment by jpesperidiao** [comment]
Checar commit [47045c2](https://github.com/dsgoficial/DsgTools/commit/47045c2a1962ba5485906dd8b1831536abd833af) do branch [3.2_dev_GenericSelection_#68](https://github.com/dsgoficial/DsgTools/tree/3.2_dev_GenericSelection_%2368

**Comment by jpesperidiao** [comment]
Commit [68e5a21](https://github.com/dsgoficial/DsgTools/commit/68e5a21705350ddfbdab46528fd683d9fec95855) do branch [3.2_dev_GenericSelection_#68](https://github.com/dsgoficial/DsgTools/tree/3.2_dev_GenericSelection_%2368).

**Comment by phborba** [comment]
Revisei e em princípio tá tudo ok. Pode fazer o pull request, ok?
