### ISSUE TITLE
Erro ao abrir tabela de atributos cobter_massa_dagua_a

### ISSUE THREAD

**Issue by HumbertoDiego** [dsgoficial/DsgTools#691]
### Assunto do problema
Erro ao abrir tabela de atributos cobter_massa_dagua_a após carregamento via DSGtools

No momento, as macros Python estão desativadas. Você Permitir que essa macro seja executada? --> SIM (Mas o erro acontece independente da escolha):

Um erro ocorreu durante a execução do seguinte código:
...
from PyQt5.QtCore import *UTF-8[13]UTF-8[13] 
from PyQt5.QtGui import *UTF-8[13]UTF-8[13] 
from PyQt5.QtWidgets import *UTF-8[13]UTF-8[13] 
from qgis import core, guiUTF-8[13]UTF-8[13] 
import reUTF-8[13]UTF-8[13] 
global aUTF-8[13]UTF-8[13] 
UTF-8[13]UTF-8[13] 
class ValidateForm:UTF-8[13]UTF-8[13] 
def __init__(self, layer, formValues, logBrowser):UTF-8[13]UTF-8[13] 
self.layer = layer UTF-8[13]UTF-8[13] 
self.formValues = formValuesUTF-8[13]UTF-8[13] 
self.rules = []UTF-8[13]UTF-8[13] 
self.logBrowser = logBrowserUTF-8[13]UTF-8[13] 
self.validateForm()UTF-8[13]UTF-8[13] 
UTF-8[13]UTF-8[13] 
def calculateExpression(self, exp):UTF-8[13]UTF-8[13] 
for field in self.formValues:UTF-8[13]UTF-8[13] 
if field != 'filter':UTF-8[13]UTF-8[13] 
if len(self.formValues[field]) == 3:UTF-8[13]UTF-8[13] 
value = self.formValues[field][1][self.formValues[field][0]]UTF-8[13]UTF-8[13] 
else:UTF-8[13]UTF-8[13] 
value = self.formValues[field][0]UTF-8[13]UTF-8[13] 
exp = exp.replace('"{0}"'.format(field), "'{0}'".format(str(value)))UTF-8[13]UTF-8[13] 
exp = exp.replace("'NULL'".format(field), "NULL")UTF-8[13]UTF-8[13] 
r = QgsExpression(exp)UTF-8[13]UTF-8[13] 
return r.evaluate()UTF-8[13]UTF-8[13] 
UTF-8[13]UTF-8[13] 
def validateForm(self):UTF-8[13]UTF-8[13] 
self.cleanRulesOnForm()UTF-8[13]UTF-8[13] 
logText = ""UTF-8[13]UTF-8[13] 
for rule in self.rules:UTF-8[13]UTF-8[13] 
for field in rule:UTF-8[13]UTF-8[13] 
if field in self.formValues:UTF-8[13]UTF-8[13] 
for exp in reversed(rule[field]):UTF-8[13]UTF-8[13] 
try:UTF-8[13]UTF-8[13] 
result = self.calculateExpression(exp['rule'])UTF-8[13]UTF-8[13] 
if bool(result):UTF-8[13]UTF-8[13] 
if len(self.formValues[field]) == 3:UTF-8[13]UTF-8[13] 
self.formValues[field][2].setStyleSheet(UTF-8[13]UTF-8[13] 
"QWidget {background-color: rgb(%s)}"%(UTF-8[13]UTF-8[13] 
exp["cor_rgb"]UTF-8[13]UTF-8[13] 
)UTF-8[13]UTF-8[13] 
)UTF-8[13]UTF-8[13] 
else:UTF-8[13]UTF-8[13] 
self.formValues[field][1].setStyleSheet(UTF-8[13]UTF-8[13] 
"QWidget {background-color: rgb(%s)}"%(UTF-8[13]UTF-8[13] 
exp["cor_rgb"]UTF-8[13]UTF-8[13] 
)UTF-8[13]UTF-8[13] 
)UTF-8[13]UTF-8[13] 
logText += u"
{0}
".format(exp["descricao"])UTF-8[13]UTF-8[13] 
except:UTF-8[13]UTF-8[13] 
passUTF-8[13]UTF-8[13] 
self.logBrowser.setText(logText)UTF-8[13]UTF-8[13] 
UTF-8[13]UTF-8[13] 
def cleanRulesOnForm(self):UTF-8[13]UTF-8[13] 
for field in self.formValues:UTF-8[13]UTF-8[13] 
if len(self.formValues[field]) == 3:UTF-8[13]UTF-8[13] 
self.formValues[field][2].setStyleSheet("") UTF-8[13]UTF-8[13] 
else:UTF-8[13]UTF-8[13] 
self.formValues[field][1].setStyleSheet("")UTF-8[13]UTF-8[13] 
UTF-8[13]UTF-8[13] 
class ManagerForm(QtCore.QObject):UTF-8[13]UTF-8[13] 
    def __init__(self, dialog, layer, feature):UTF-8[13]UTF-8[13] 
        super(ManagerForm, self).__init__()UTF-8[13]UTF-8[13] 
        self.myDialog = dialogUTF-8[13]UTF-8[13] 
        self.lyr = layerUTF-8[13]UTF-8[13] 
        self.validadeForm = ""UTF-8[13]UTF-8[13] 
        self.logBrowser = dialog.findChild(QLabel, "logLabel")UTF-8[13]UTF-8[13] 
        self.logFrame = dialog.findChild(QFrame, "logFrame")UTF-8[13]UTF-8[13] 
        self.logFrame.hide()UTF-8[13]UTF-8[13] 
        self.logBtn = dialog.findChild(QPushButton, "logBtn")UTF-8[13]UTF-8[13] 
        self.logBtn.setCheckable(True)UTF-8[13]UTF-8[13] 
        self.logBtn.clicked.connect(self.showLog)UTF-8[13]UTF-8[13] 
        buttonBox = dialog.findChild(QDialogButtonBox,"buttonBox")UTF-8[13]UTF-8[13] 
        buttonBox.rejected.connect(self.finishedForm)UTF-8[13]UTF-8[13] 
        buttonBox.accepted.connect(self.finishedForm)UTF-8[13]UTF-8[13] 
        button_ok = buttonBox.button(QDialogButtonBox.Ok)UTF-8[13]UTF-8[13] 
        button_ok.setAutoDefault(True)UTF-8[13]UTF-8[13] 
        button_ok.setDefault(True)UTF-8[13]UTF-8[13] 
        button_cancel = buttonBox.button(QDialogButtonBox.Cancel)UTF-8[13]UTF-8[13] 
        button_cancel.setAutoDefault(False)UTF-8[13]UTF-8[13] 
        button_cancel.setDefault(False)UTF-8[13]UTF-8[13] 
        self.myDialog.installEventFilter(self)UTF-8[13]UTF-8[13] 
UTF-8[13]UTF-8[13] 
    def showLog(self, state):UTF-8[13]UTF-8[13] 
        if state:UTF-8[13]UTF-8[13] 
            self.logFrame.show()UTF-8[13]UTF-8[13] 
        else:UTF-8[13]UTF-8[13] 
            self.logFrame.hide()UTF-8[13]UTF-8[13] 
UTF-8[13]UTF-8[13] 
    def eventFilter(self, o, event):UTF-8[13]UTF-8[13] 
        if event.type() in [7, 10, 11, 100]:UTF-8[13]UTF-8[13] 
            self.validateLayerByRules()UTF-8[13]UTF-8[13] 
        return FalseUTF-8[13]UTF-8[13] 
UTF-8[13]UTF-8[13] 
    def validateLayerByRules(self):UTF-8[13]UTF-8[13] 
        formValues = {}UTF-8[13]UTF-8[13] 
        for cb in self.myDialog.findChildren(QComboBox):UTF-8[13]UTF-8[13] 
            idx = self.lyr.fields().indexOf(cb.objectName())UTF-8[13]UTF-8[13] 
            formValues[cb.objectName()] = [UTF-8[13]UTF-8[13] 
                cb.currentText(),UTF-8[13]UTF-8[13] 
                self.lyr.editorWidgetSetup(idx).config()['map'] if idx > 0 else self.optFilter.keys(),UTF-8[13]UTF-8[13] 
                cbUTF-8[13]UTF-8[13] 
            ]UTF-8[13]UTF-8[13] 
        for le in self.myDialog.findChildren(QLineEdit):UTF-8[13]UTF-8[13] 
                formValues[le.objectName()] = [UTF-8[13]UTF-8[13] 
                le.text(),UTF-8[13]UTF-8[13] 
                leUTF-8[13]UTF-8[13] 
            ]UTF-8[13]UTF-8[13] 
        self.validadeForm = ValidateForm(self.lyr, formValues, self.logBrowser)UTF-8[13]UTF-8[13] 
UTF-8[13]UTF-8[13] 
    def finishedForm(self):UTF-8[13]UTF-8[13] 
        passUTF-8[13]UTF-8[13] 
UTF-8[13]UTF-8[13] 
def formOpen(dialog, layer, featureid):UTF-8[13]UTF-8[13] 
    try:UTF-8[13]UTF-8[13] 
        global aUTF-8[13]UTF-8[13] 
        a = ManagerForm(dialog, layer, featureid)UTF-8[13]UTF-8[13] 
    except:UTF-8[13]UTF-8[13] 
        pass

  File "", line 2
    from PyQt5.QtCore import *UTF-8[13]UTF-8[13]
                              ^
SyntaxError: invalid syntax

Versão do Python:
3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]

Versão do QGIS:
3.24.3-Tisler 'Tisler', cf22b74e

Caminho para o Python:
['C:\\Users/Administrador/AppData/Roaming/QGIS/QGIS3\\profiles\\3.24-default/python/plugins\\lftools', 'C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python', 'C:/Users/Administrador/AppData/Roaming/QGIS/QGIS3\\profiles\\3.24-default/python', 'C:/Users/Administrador/AppData/Roaming/QGIS/QGIS3\\profiles\\3.24-default/python/plugins', 'C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins', 'C:\\Program Files\\QGIS 3.24.3\\bin\\python39.zip', 'C:\\PROGRA~1\\QGIS32~1.3\\apps\\Python39\\DLLs', 'C:\\PROGRA~1\\QGIS32~1.3\\apps\\Python39\\lib', 'C:\\Program Files\\QGIS 3.24.3\\bin', 'C:\\PROGRA~1\\QGIS32~1.3\\apps\\Python39', 'C:\\PROGRA~1\\QGIS32~1.3\\apps\\Python39\\lib\\site-packages', 'C:\\PROGRA~1\\QGIS32~1.3\\apps\\Python39\\lib\\site-packages\\GDAL-3.4.3-py3.9-win-amd64.egg', 'C:\\PROGRA~1\\QGIS32~1.3\\apps\\Python39\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGIS32~1.3\\apps\\Python39\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGIS32~1.3\\apps\\Python39\\lib\\site-packages\\Pythonwin', 'C:/Users/Administrador/AppData/Roaming/QGIS/QGIS3\\profiles\\3.24-default/python', 'C:\\Users/Administrador/AppData/Roaming/QGIS/QGIS3\\profiles\\3.24-default/python/plugins\\ferramentas_edicao\\modules\\qrcode', 'C:\\Users\\Administrador\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\3.24-default\\python\\plugins\\DsgTools', 'C:\\Users\\Administrador\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\3.24-default\\python\\plugins\\DSGTools_Op\\auxiliar', 'C:\\Users\\Administrador\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\3.24-default\\python\\plugins\\DSGTools_Op\\QuickGeocoder\\dependencies']

EM SEGUIDA (me parece a parte principal do erro):

```
Um erro ocorreu enquanto executava o código Python: 

SystemError: returned a result with an error set 
Traceback (most recent call last):
  File "", line 1, in 
NameError: name 'formOpen' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users/Administrador/AppData/Roaming/QGIS/QGIS3\profiles\3.24-default/python/plugins\DsgTools\core\DSGToolsProcessingAlgs\dsgtoolsProcessingAlgorithmProvider.py", line 392, in icon
    return QIcon(':/plugins/DsgTools/icons/dsg.png')
SystemError:  returned a result with an error set
```

Versão do Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versão do QGIS: 3.24.3-Tisler Tisler, cf22b74e 

Caminho do Python:
C:\Users/Administrador/AppData/Roaming/QGIS/QGIS3\profiles\3.24-default/python/plugins\lftools
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python
C:/Users/Administrador/AppData/Roaming/QGIS/QGIS3\profiles\3.24-default/python
C:/Users/Administrador/AppData/Roaming/QGIS/QGIS3\profiles\3.24-default/python/plugins
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.24.3\bin\python39.zip
C:\PROGRA~1\QGIS32~1.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib
C:\Program Files\QGIS 3.24.3\bin
C:\PROGRA~1\QGIS32~1.3\apps\Python39
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\GDAL-3.4.3-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Administrador/AppData/Roaming/QGIS/QGIS3\profiles\3.24-default/python
C:\Users/Administrador/AppData/Roaming/QGIS/QGIS3\profiles\3.24-default/python/plugins\ferramentas_edicao\modules\qrcode
C:\Users\Administrador\AppData\Roaming\QGIS\QGIS3\profiles\3.24-default\python\plugins\DsgTools
C:\Users\Administrador\AppData\Roaming\QGIS\QGIS3\profiles\3.24-default\python\plugins\DSGTools_Op\auxiliar
C:\Users\Administrador\AppData\Roaming\QGIS\QGIS3\profiles\3.24-default\python\plugins\DSGTools_Op\QuickGeocoder\dependencies

EM OUTRA JANELA:

A função python init (formOpen) não foi encontrada!
Verifique o nome da função na aba Campos das propriedades da camada.

**Comment by phborba** [comment]
Boa tarde Diego, tudo bem? Isso me parece problema de formulário custom, não do DSGTools. Como você criou esse formulário?

**Comment by phborba** [comment]
@HumbertoDiego o bug permanece ou eu posso fechar o issue?

**Comment by HumbertoDiego** [comment]
Bom dia, desculpe a demora. Pode fechar. Refiz os testes em um novo projeto do QGIS e não existe mais erro, vou investigar um pouco mais a causa, talvez tenha sido formulários criados em outras máquinas que ficam salvo no projeto, o arquivo de projeto .qgs fica passando de mão em mão bugando todo mundo.

**Comment by phborba** [comment]
Obrigado pelo retorno, fechei aqui. Qualquer problema, entra em contato aí! Um abraço

**Comment by HumbertoDiego** [comment]
Entendi a causa. 
O Ferramentas de produção cria um formulário no caminho _C:\Users/NOMEUSUARIO/AppData/Roaming/QGIS/QGIS3\profiles\3.24-default/python/plugins\Ferramentas_Producao\Tools\LoadData\forms\DATABASENAME-CLASSNAME.ui_, se alguém atualizar o estilo no banco vai registrar na tabela public.layer_styles o caminho inválido.
O DSGTOOLS ao puxar o MI do banco vai vim com o estilo contendo um formulário com caminho inválido, repercutindo o erro para todos.
Uma sugestão seria reforçar a função formOpen para retornar o formulário default caso qq erro aconteça.
