### ISSUE TITLE
A caixa de ferramenta de classificação de feição não abre na versão 3.22 do QGIS.

### ISSUE THREAD

**Issue by LFP-Trabalho** [dsgoficial/DsgTools#703]
### Subject of the issue (Assunto do problema)
A caixa de ferramenta de classificação de feição não abre na versão 3.22 do QGIS.

### Your environment (Seu ambiente)
* Windows 10 (Seu sistema operacional): 
* 3.22.4 (Versão do QGIS): 
* 4.4 (Versão do DSGTools): 

### Steps to reproduce (Passos para reproduzir)
Abrir a caixa de ferramenta classificação de feições (Custom Feature Toolbox). 

![Captura de tela 2022-08-11 113247](https://user-images.githubusercontent.com/81705409/184158480-d67d10c7-2b56-4bd9-9d8e-2e3dcf8b0e58.jpg)

**Comment by phborba** [comment]
Bom dia, você precisa configurar o menu de aquisição (a configuração dos botões, por meio do botão adicionar) e, após a criação dos seus botões, apertar em criar menu após a configuração.

**Comment by phborba** [comment]
@LFP-Trabalho passei para o seu chefe, o Perrut, um vídeo mostrando como se faz, por gentileza pede pra ele compartilhar contigo.
