### ISSUE TITLE
Problema ao carregar estilos com a ferramenta Load layers from a server

### ISSUE THREAD

**Issue by franciscocamellon** [dsgoficial/DsgTools#717]
### Subject of the issue (Assunto do problema)
Ao carregar um banco de dados não aparecem os estilos disponíves para carregar de acordo com a versão do banco.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Windows 10
* version of QGIS (Versão do QGIS):  3.22.9
* version of DSGTools (Versão do DSGTools):  4.5.0

### Steps to reproduce (Passos para reproduzir)
- Clicar na ferramenta load layers;
- Escolher um banco de dados;
- Selecionar os layers a serem carregados;
- Escolher um estilo disponível;
- Clicar no botão OK.
- Não aparecem as pastas com estilos

### Expected behaviour (Comportamento esperado)
É esperado que a ferramenta mostre as pastas com os estilos disponíveis.

### Actual behaviour (Comportamento atual)
A ferramenta mostra a mensagem "No available layers"

### Debug
https://github.com/dsgoficial/DsgTools/blob/321089eaf270efcd97037cb082ae65053931a545/DsgTools/core/Factories/DbFactory/abstractDb.py#L639

Verifiquei que no método acima a variável _**dbVersion**_ recebida tem o valor de "EDGV 3.0" quando deveria receber '2.1.3', '2.1.3 Pro', '3.0', '3.0 Pro' ou 'FTer_2a_Ed'. Ao corrigir o valor no método **abstractDb** a ferramenta apresenta o comportamento esperado.

**Comment by phborba** [comment]
Boa tarde @franciscocamellon , tudo bem?

Vamos refatorar essa parte dos estilos. A ideia é não importar mais para o banco e dar a opção de carregar apontando o caminho. Para os casos de carregar direto do banco, temos o SAP, aí para não perdermos o caso de uso de carregar um estilo pelo DSGTools, vamos mudar para essa forma.

A forma que hoje em dia funciona no DSGTools sempre me incomodou, dado que precisa copiar os arquivos de estilo para pastas específicas dentro do DSGTools. Com essa nova forma que pensamos, vamos tambem refatorar a barra de ferramentas de estilo, trocando por uma ferramenta mais bizurada que funcionaria por um atalho.
