### ISSUE TITLE
Caixa de Ferramentas de Validação (interface): Histórico por usuário

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#73]
Deseja-se que no histórico de validação, além do processo e horário de execução, seja guardado o usuário que executou o procedimento.

**Comment by jpesperidiao** [comment]
Esse issue já não foi resolvido no issue [177](https://github.com/dsgoficial/DsgTools/issues/177)?

**Comment by jpesperidiao** [comment]
Acho que entendi e tenho uma ideia de como fazer. Vou implementar o que eu acho que é e, assim que tiver um "MVP", aviso aqui, pode ser?

**Comment by phborba** [comment]
Blz, sem problemas

**Comment by phborba** [comment]
Pull request e merge feitos.
