### ISSUE TITLE
Crash com Identificar e Consertar Geometrias Inválidas

### ISSUE THREAD

**Issue by lcoandrade** [dsgoficial/DsgTools#763]
### Subject of the issue (Assunto do problema)
Ao rodar o processo Identificar e Consertar Geometrias Inválidas com uma camada de polígonos (CAMARONERAS.shp) o QGIS cai.

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): macOS Ventura 13.4
* version of QGIS (Versão do QGIS): 3.30.2-'s-Hertogenbosch
* version of DSGTools (Versão do DSGTools):4.8.0

### Steps to reproduce (Passos para reproduzir)
Carregar a camada de polígonos, iniciar o processo  Identificar e Consertar Geometrias Inválidas e marcar a opção de consertar geometrias da camada de entrada.

### Expected behaviour (Comportamento esperado)
Consertar as geometrias.

### Actual behaviour (Comportamento atual)
O QGIS quebra e é encerrado abruptamente.
[camaroneras.zip](https://github.com/dsgoficial/DsgTools/files/11821358/camaroneras.zip)

**Comment by phborba** [comment]
No windows não consegui replicar o bug, vou rodar no mac para ver se consigo.

**Comment by phborba** [comment]
Também não consegui replicar no macOS ventura.

**Comment by phborba** [comment]
E outra coisa, self intersect o DSGTools não corrige. Teria que corrigir manualmente.

**Comment by phborba** [comment]
Como não conseguimos replicar, vou fechar. Qualquer coisa, se tiver o bug novamente, por gentileza nos avise que vamos corrigir!

**Comment by lcoandrade** [comment]
Agora, nem eu mais consigo replicar... 🤣🤣🤣
