### ISSUE TITLE
Caixa de Ferramentas de Validação (interface): Habilitar ou desabilitar cardinalidade nas regras espaciais

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#77]
Atualmente é obrigatório o preenchimento da cardinalidade em relacionamentos espaciais. Deseja-se que para alguns tipos de verificação esse preenchimento seja opcional.

**Comment by jpesperidiao** [comment]
Feito no commit [4684bf8](https://github.com/dsgoficial/DsgTools/commit/4684bf817e30307d9c618c5d0ba599e1792bcf69) do branch [3.2_dev_ValidationToolbox_%2377](https://github.com/dsgoficial/DsgTools/tree/3.2_dev_ValidationToolbox_#77).
