### ISSUE TITLE
Conversão de Bancos de Dados: Conversão da EDGV Pro  para EDGV 2.1.3

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#83]
Deseja-se que seja elaborado um conversor da EDGV Pro (anteriormente chamada de EDGV Sumarizada) para a EDGV 2.1.3. Essa funcionalidade permitirá que se adquira o conhecimento para outras conversões de modelagem, como a solicitada na próxima melhoria.

**Comment by dinizime** [comment]
O JSON de mapeamento está pronto, faltando somente que o conversor de modelagens do DSGTools siga esse padrão.
