### ISSUE TITLE
Ferramentas para aquisição em Linha-Centroide: Uso de áreas já construídas na cobertura terrestre como injunção

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#93]
Deseja-se que áreas já construídas na cobertura terrestre possam ser usadas como injunção para o processo de fechamento de áreas a partir de linhas e centroides, ou seja, dado um conjunto de áreas da cobertura já construídas, utilizá-las no processo de fechamento. Como exemplo, pode-se citar o seguinte procedimento: considere uma cobertura terrestre composta por Área Edificada, Massa D’água, Trecho Massa D’água e as classes da Vegetação. Nesse procedimento, deseja-se trabalhar com linha e centroide somente na construção da vegetação, dado que as demais áreas vem como insumo de outras etapas. Dessa forma, seriam adquiridos os centroides e as linhas que fecham as vegetações e a rotina de fechamento de áreas verificaria as áreas fechadas com as já existentes, diferentemente do processo atual, que considera que todas as áreas da cobertura terrestre serão oriundas de linhas e centroides.

**Comment by phborba** [comment]
@dinizime pode testar pra mim por favor?

**Comment by jpesperidiao** [comment]
@phborba, a princípio este é um _issue_ resolvido pelo alg "Build polygons from center points and boundaries", correto? Posso atribuir a você encerrar?

**Comment by phborba** [comment]
Exato! Pode sim =]
