### ISSUE TITLE
Ferramenta de Complexos: Zoom para elemento

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#94]
Atualmente, está disponível no DSGTools a funcionalidade de zoom para complexo. Deseja-se zoom para elementos que compõem determinado complexo.

**Comment by dinizime** [comment]
@phborba você tinha mencionado algo que tornada sem efeito esse issue. Procede?

**Comment by phborba** [comment]
Era somente o fato de não fazermos mais complexos, da 3.0 não ter complexos implementados e que a ferramenta de complexos estava se tornando obsoleta.
