### ISSUE TITLE
Nova Funcionalidade: Seccionar linhas sobrepostas de classes distintas

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#98]
Neste processo, linhas que se sobrepõem ou se intersectam são confrontadas entre si e o resultado dessa operação vetorial são linhas seccionadas. Deseja-se um comportamento idêntico ao transformer do FME Line on Line Overlayer.

**Comment by phborba** [comment]
Nos testes que fiz, o topological clean fez isso. @dinizime e @lcoandrade vcs podem testar?

**Comment by lcoandrade** [comment]
As linhas foram seccionadas aqui. O resultado do topologicalClean é o esperado nesta issue.

**Comment by phborba** [comment]
O clean não faz em 100% dos casos. Reabri a issue e vai existir um processo só para isso.
