### ISSUE TITLE
Nova Funcionalidade: Unir linhas

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#99]
Nesse processo, linhas que se tocam e possuem mesmo conjunto de atributos devem ser unidas. Deseja-se um comportamento idêntico ao transformer do FME Line Joinner.

Casos de uso a serem atendidos:
1- Linhas com mesmo conjunto de atributos devem ser unidos (atributos a serem ignorados devem ser informados por meio de black list)
2- Linhas que são candidatas a união se relacionam somente entre si (para cada nó de intersecção de linhas, só pode ter 2 linhas como candidatas)

Sugestão de passos para implementação:
- [ ] Calcular os pontos de início e fim de trechos
- [ ] Iterar sobre os pontos, pegar aqueles que tem dois candidatos e unir os candidatos com mesma tupla
- [ ] Calcular novamente os pontos. Repetir os passos até que não existam mais pontos que relacionem 2 e somente 2 trechos.

**Comment by lcoandrade** [comment]
Como vc está de férias resolvi assumir a issue. Fiz o processo e testei aqui num caso pequeno e funcionou. Preciso de mais testes para verificar se está tudo ok mesmo. Feito no commit c26c0bb.

**Comment by lcoandrade** [comment]
@dinizime, @rsmaior podem testar pra me dizer o que acham?
Os atributos que devem ser considerados devem ser inseridos separados por vírgula, mas pode ser somente um...

**Comment by lcoandrade** [comment]
Lembrando que eu coloquei a restrição de que as linhas devem estar se tocando e não se intersectando.

**Comment by phborba** [comment]
Testei e achei alguns problemas. Atualizei a descrição para descrever melhor o problema

**Comment by lcoandrade** [comment]
Resolvi deixar o código original e colocar como pós processo o Limpar Geometrias. Assim se chega ao efeito desejado sem reinventar a roda. Feito no commit 24dc164.

**Comment by lcoandrade** [comment]
Agora com black list no commit 8a2afa3. Issue encerrada.

**Comment by phborba** [comment]
O processo implementado não atende aos requisitos da validação para a linha de produção. Será reimplementado.

**Comment by lcoandrade** [comment]
Por que a necessidade de reimplementar? Quais requisitos não são atendidos? É o problema que vc mencionou de algumas linhas sumirem devido ao Limpar Geometrias no pós-processo? Não é o caso investigar o motivo do problema ao invés de refazer o processo?

**Comment by phborba** [comment]
O processo que originalmente foi concebido foi para tratar peculiaridades da linha de produção, na criação de pontos de acordo com as regras da adgv e a união dos segmentos baseados nos pontos. O processo atual não respeita, por exemplo, o seccionamento de trechos internos a trechos de massa d’água. Com os problemas de sumiço de trechos, a gerência do projeto sentiu a necessidade de rever a implementação desse processo.

**Comment by lcoandrade** [comment]
Se a gerência decidiu, está decidido...

**Comment by phborba** [comment]
Alterei alguns parâmetros no clean, rodei um remove duplicates e rodei o clean novamente e sumiram mais da metade das feições, não estou entendendo o porquê.

**Comment by phborba** [comment]
No output do grass saiu coisa, o problema provavelmente está no updateOriginalLayer
